### ISSUE TITLE
Support different import names

### ISSUE THREAD

**Issue by mxstbr** [styled-components/babel-plugin-styled-components#1]
Currently, this breaks the babel plugin:

```JS
import s from 'styled-components'
```

Instead of hard-coding and checking for the `styled` keyword, we should be looking for the import declaration and getting the variable name. (what I do [here](https://github.com/styled-components/stylelint-processor-styled-components/blob/9d904c963466e397de2d08f84314249d9c0e7ce9/src/index.js#L60-L63) and [here](https://github.com/styled-components/stylelint-processor-styled-components/blob/9d904c963466e397de2d08f84314249d9c0e7ce9/src/utils/parse.js#L5-L23) in the stylelint processor)

**Comment by vdanchenkov** [comment]
Initially I wanted to keep it usable for https://github.com/threepointone/glamor/blob/master/docs/styled.md and similar cases where `styled` is not imported from `styled-components`. We could came up with some sophisticated configuration, or just support both cases: current behaviour and suggested in this issue.

**Comment by mxstbr** [comment]
There's a lot more this plugin is going to do which won't work for `glamor` at all.

We should _default_ to `styled`, but if there's an `import whatever from 'styled-components'` we take whatever variable that's assigned to. (that's what the stylelint processor does too)
