### ISSUE TITLE
Identifiers in test fixtures affected by tests order.

### ISSUE THREAD

**Issue by vdanchenkov** [styled-components/babel-plugin-styled-components#10]
Looks like currently tests runs in alphabetical order and if I create test in the middle, it affects ids generated for components in all tests which runs after it.

My ideas are: introduce internal id counter reset method or explicitly set order of tests.

**Comment by mxstbr** [comment]
Yeah I noticed this. I like your second solution, let's prefix all folder names with numbers and strip them from `index.test.js`? `1-should-add-display-name`,...

**Comment by vdanchenkov** [comment]
I like prefixes. Two-digit will be enough: 01, 02... Will do.
