### ISSUE TITLE
Exporting a styled component as default leads to `Prop `className` did not match.`-Warning

### ISSUE THREAD

**Issue by zeemawn** [styled-components/babel-plugin-styled-components#102]
Referenced from https://github.com/styled-components/styled-components/issues/1272

## Version
2.2.2
babel-plugin-styled-components: 1.3.0

## Reproduction
Exporting a styled component as default leads to `Prop `className` did not match.`-Warning

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

## Steps to reproduce
Create a JS-file, e.g. named "Flex.js" in which you directly export a styled component:

```
import styled from 'styled-components'

export default styled.div`
    display: inline-flex;
`
```

## Expected Behavior
No warning in browser-console

## Actual Behavior
Warning in the form of ```Warning: Prop 'className' did not match. Server: "Flex-s1rf88eb-0 dMObJs" Client: "Flex___default-s1rf88eb-0 bunKfG"```

**Comment by philpl** [comment]
I think we'll need some more information here:

- Is there anything specific to the exported component (a code snippet would be amazing)
- What's the babel config and transpilation setup? i.e. does it run before the modules plugin
- Is the SSR option turned on (looks like it is)

**Comment by joetidee** [comment]
I am getting this error too.

**Comment by cdebotton** [comment]
Also having this problem. I've noticed that the problem only seems to occur when `react-hot-loader/babel` (@next) is enabled.

**Comment by probablyup** [comment]
@zeemawn You might find this helpful: https://www.npmjs.com/package/babel-plugin-transform-export-default-name
