### ISSUE TITLE
File hash in displayName is too fragile

### ISSUE THREAD

**Issue by RamIdeas** [styled-components/babel-plugin-styled-components#105]
Using a hash of the file contents when generating the displayName causes snapshot tests to fail frequently and unnecessarily. Changes to my files that don't effect the component require me to update my snapshots - the false negatives kind of make them redundant.

I assume the reason for the file hash is to make the class name unique, as 2 components could possibly have the same name.

Would it not make more sense, and be less fragile, to use a hash of the file path?

**Comment by philpl** [comment]
This is why we have: https://github.com/styled-components/jest-styled-components

**Comment by probablyup** [comment]
@philpl I did some similar work for emotion and I'm in agreement that hashing the file contents is a bad idea. This becomes particularly visible when there's a difference in environment variable handling between client and server, which in the current algorithm would lead to a hash break.

**Comment by probablyup** [comment]
Here's the algorithm used in emotion currently: https://github.com/emotion-js/emotion/blob/master/packages/babel-plugin-emotion/src/index.js#L121-L126 (note that it has the same problem as styled-components at the moment)

**Comment by mxstbr** [comment]
@probablyup do you mean you implemented the same algorithm we have right now or a better one? Do you have any better ideas?

**Comment by probablyup** [comment]
@mxstbr It's almost the same. I think there might be some minor differences in how the file path is normalized.

When I was working on it with @mitchellhamilton I believe the only reason why the file contents were being added to the hash were for cases when the babel plugin was being used in a virtual file system (where path might not be available.)

If that's also the case for styled-components, we should be able to avoid including the file content in the hash as long as the filepath is available. This would be a better experience for the 99% case, but still support the edge case as a fallback.

**Comment by mxstbr** [comment]
That sounds very reasonable. Wanna submit a patch for that?

**Comment by probablyup** [comment]
@mxstbr I think https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L32 is also part of the problem. If the execution order of the components is different in a server vs client config, I believe that would cause the component # to be different and break the hash

**Comment by mxstbr** [comment]
Yeah that makes sense—why do we have that in the first place? Does the blame tell you anything?

**Comment by probablyup** [comment]
It was added a long time ago in https://github.com/styled-components/styled-components/commit/6e14952ad5aa160740cd52e33ff7cff7bbbfbd94. No obvious reasoning for it though. @geelen, do you remember?
