### ISSUE TITLE
transpileTemplateLiterals not extend

### ISSUE THREAD

**Issue by stephenway** [styled-components/babel-plugin-styled-components#106]
For some reason when I build a module with `transpileTempalteLiterals: true` my extends are not included in transpilation. Is this to be expected?

**Comment by philpl** [comment]
Yes, those are unsupported right now by the Babel plugin which does cause some issues.

You can use styled() right now to circumvent this. We’re currently discussing how to fix this by either deprecating extend or introducing an internal APi that would make the ssr option work correctly.

If you only need extend, the option you’re using is fully optional if you’re transpiling with, for instance, Babel-preset-env.

**Comment by stephenway** [comment]
I might give styled() a try, thanks for the suggestion and prompt reply!

**Comment by stephenway** [comment]
Is this a duplicate of #79? If so, I can close it.

**Comment by philpl** [comment]
Oh it is indeed! Good catch :) i totally forgot about that one
