### ISSUE TITLE
Unknown plugin "babel-plugin-styled-components" 

### ISSUE THREAD

**Issue by yairkukielka** [styled-components/babel-plugin-styled-components#107]
Hi, I'm having this problem in my project, using nextjs 4. In my .babelrc file I have this:

```{
  "env": {
    "development": {
      "presets": "next/babel",
      "plugins": [
        [
          "babel-plugin-styled-components",
          { "ssr": true, "displayName": false, "preprocess": false }
        ]
      ]
    },
    "production": {
      "presets": "next/babel",
      "plugins": [
        [
          "babel-plugin-styled-components",
          { "ssr": true, "displayName": false, "preprocess": false }
        ]
      ]
    },
    "test": {
      "presets": [
        [
          "env",
          {
            "modules": "commonjs"
          }
        ],
        "next/babel"
      ],
      "sourceMaps": true,
      "retainLines": true
    }
  }
}
```

Then, I run `yarn install --production` and then `yarn build` I get `Unknown plugin "babel-plugin-styled-components"`. My objective is to have the minimum number of dependencies in my docker container for production, that's why I don't install the devDepenencies.

What I want to know is whether this package should be in the dependencies part of packages.json or in the devDependencies one. And if it's needed in the dependencies for production, I think it should be stated in the docs (in the docs it looks like it's a dev dependency, see: https://www.styled-components.com/docs/tooling)

**Comment by philpl** [comment]
`yarn install --production` => this command doesn't install any `devDependencies` so I guess the issue lies there

**Comment by yairkukielka** [comment]
yes, so shouldn't it be advertised as a production module? The docs state this is the way of installing it:
`npm install --save-dev babel-plugin-styled-components`

I just want to confirm whether it's not just a dev dependency. And if it's not, the docs should maybe say that this is how you install it:
`npm install --save babel-plugin-styled-components`

**Comment by TrySound** [comment]
@yairkukielka It's development plugin for better dx. Just remove it from production env

**Comment by TrySound** [comment]
@yairkukielka However yeah, there're ssr or minifications options for production. But it's edge case. You decide how to use it.

**Comment by mxstbr** [comment]
No it should definitely be used in production.

**Comment by mxstbr** [comment]
The `devDependency` vs `dependency` split doesn't really make any sense for frontend projects. That being said, the convention is to put any build tooling into `devDependencies` and everything that is actually bundled into the client-side JavaScript into `dependencies`.
