### ISSUE TITLE
Won't install as a plugin in webpack.base.babel.js

### ISSUE THREAD

**Issue by lgerndt** [styled-components/babel-plugin-styled-components#110]
Hi, while I haven't ejected, the react project I inherited isn't using react-scripts, and does provide me access to webpack configs.  So in webpack.base.babel.js I do this at the top:

`const babelPluginStyledComponents = require('html-webpack-plugin');`

And in the plugins arrays, I do this:

```
plugins: options.plugins.concat([
  babelPluginStyledComponents,
  ...

```
But attempting to build, i get this error:

babelPluginStyledComponents { default: [Function] }
/Users/lgerndt/Sites/my-account/node_modules/tapable/lib/Tapable.js:375
		arguments[i].apply(this);
		             ^
```
TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/lgerndt/Sites/my-account/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/lgerndt/Sites/my-account/node_modules/webpack/lib/webpack.js:32:19)
    at addDevMiddlewares (/Users/lgerndt/Sites/my-account/server/middlewares/frontendMiddleware.js:12:20)
    at module.exports (/Users/lgerndt/Sites/my-account/server/middlewares/frontendMiddleware.js:69:5)
    at Object.<anonymous> (/Users/lgerndt/Sites/my-account/server/index.js:17:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```
I've also tried "new babelPluginStyledComponents()", didn't work, and "[babelPluginStyledComponents]", no joy.  Help Wanted :)

**Comment by mxstbr** [comment]
```
const babelPluginStyledComponents = require('html-webpack-plugin');

babelPluginStyledComponents = require('html-webpack-plugin')

babelPluginStyledComponents

require('html-webpack-plugin')

html-webpack-plugin
```

You might wanna change that to `require('babel-plugin-styled-components')`. 😆

**Comment by lgerndt** [comment]
sorry, I had already corrected that and still got the same problem.  Do you think it should work?

**Comment by philpl** [comment]
Im not sure what you’re concatenating it to but if I read the error correctly you might be trying to use it as a webpack plugin rather than a Babel plugin.

In case that’s accidental, you will need to use the Babel-loader with webpack and let Babel load the plugin instead :)

**Comment by lgerndt** [comment]
Thanks for replying @philpl. I hear you about unrelated, but I'll post what you requested (and sure appreciate you looking!)

I just learned today that our app was not a CRA app to begin with, I'm not sure that matters.

`const path = require('path');
const webpack = require('webpack');
process.noDeprecation = true;
const styleComponentsBabelPlugin = require('babel-plugin-styled-components');
module.exports = (options) => {
  const buildDir = path.resolve(process.cwd(), 'build');
  const appDir = path.resolve(process.cwd(), 'app');
  const buildConfig = 'config.json';
  const devConfig = 'dev-config.json';
  const configDir = process.env.NODE_ENV !== 'development' ? buildDir : appDir;
  const configFile = process.env.NODE_ENV !== 'development' ? buildConfig : devConfig;

  return ({
    entry: options.entry,
    output: Object.assign({ // Compile into js/build.js
      path: path.resolve(process.cwd(), 'build'),
      publicPath: '/',
    }, options.output), // Merge with env dependent settings
    module: {
      loaders: [{
        test: /\.js$/, // Transform all .js files required somewhere with Babel
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: options.babelQuery,
      }, {
        // Do not transform vendor's CSS with CSS-modules
        // The point is that they remain in global scope.
        // Since we require these CSS files in our JS or CSS files,
        // they will be a part of our compilation either way.
        // So, no need for ExtractTextPlugin here.
        test: /\.css$/,
        include: /node_modules/,
        loaders: ['style-loader', 'css-loader'],
      }, {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        loader: 'file-loader',
      }, {
        test: /\.(jpg|png|gif)$/,
        loaders: [
          'file-loader',
          {
            loader: 'image-webpack-loader',
            query: {
              progressive: true,
              optimizationLevel: 7,
              interlaced: false,
              pngquant: {
                quality: '65-90',
                speed: 4,
              },
            },
          },
        ],
      }, {
        test: /\.html$/,
        loader: 'html-loader',
      }, {
        test: /\.json$/,
        loader: 'json-loader',
      }, {
        test: /\.(mp4|webm)$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
        },
      }],
    },
    plugins: options.plugins.concat([

      styleComponentsBabelPlugin,

      new webpack.ProvidePlugin({
        // make fetch available
        fetch: 'exports-loader?self.fetch!whatwg-fetch',
        jQuery: 'jquery',
        $: 'jquery',
      }),
      new webpack.IgnorePlugin(/(locale)/, /node_modules.+(momentjs)/),   // fixes a build error: Module not found: Error: Can't resolve './locale' in '.../node_modules/moment/src/lib/locale'

      // Always expose NODE_ENV to webpack, in order to use `process.env.NODE_ENV`
      // inside your code for any environment checks; UglifyJS will automatically
      // drop any unreachable code.

      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify('production'),
          APP_VERSION: JSON.stringify('3.1'),
          BUILD_TIME: JSON.stringify(Date()),
        },
      }),
      new webpack.NamedModulesPlugin(),
    ]),
    resolve: {
      alias: {
        qamConfig: path.resolve(configDir, configFile),
      },
      modules: ['app', 'node_modules'],
      extensions: [
        '.js',
        '.jsx',
        '.react.js',
      ],
      mainFields: [
        'browser',
        'jsnext:main',
        'main',
      ],
    },
    node: { // this entry is solely for suppressing errors:
      net: 'empty',
      tls: 'empty',
    },
    devtool: options.devtool,
    target: 'web', // Make web variables accessible to webpack, e.g. window
    performance: options.performance || {},
  });
};
`
