### ISSUE TITLE
Support for babel 7

### ISSUE THREAD

**Issue by darkowic** [styled-components/babel-plugin-styled-components#116]
Add support for babel 7.

Babel 7 is still in beta version but already many developers is using it - https://www.npmjs.com/package/@babel/cli

In react 16.2.0 release blog they recomend new babel version
https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#babel

**Comment by mxstbr** [comment]
Pretty sure @lixiaoyan added support for that in #84. In case you're experiencing any specific errors with Babel 7 please open a new issue with the full logs! Thanks!

**Comment by darkowic** [comment]
Hmm ok. I posted this issue here because I saw in package.json old `babel-types` in dependencies. Now the package is in babel scope https://github.com/babel/babel/tree/master/packages/babel-types

**Comment by mxstbr** [comment]
PR to move that welcome!

**Comment by damassi** [comment]
https://github.com/styled-components/babel-plugin-styled-components/pull/128
