### ISSUE TITLE
Mangled CSS output when minification is turned ON

### ISSUE THREAD

**Issue by mattiascaricato** [styled-components/babel-plugin-styled-components#118]
Hey,

I'm experiencing mangled CSS results when I turn the minify option on.

This is the component code:
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';
import escmStyles from 'ek-web-css-variables';

const NoResultsWrapper = styled.div`
  text-align: center;
  color: ${escmStyles.grey3};

  p {
    margin: 0;
  }
`;

const Message = styled.span`
  font: ${escmStyles.elTitle4Sb}
`;

const Description = styled.span`
  font: ${escmStyles.elDisplay2}
`;

const NoResults = ({ message, description }) => (
  <NoResultsWrapper>
    <p><Message>{message}</Message></p>
    <p><Description>{description}</Description></p>
  </NoResultsWrapper>
);

NoResults.propTypes = {
  message: PropTypes.string.isRequired,
  description: PropTypes.string.isRequired
};

export default NoResults;
```

As you can see in the image below, when I turn on minification there are no styles applied at all:
![image](https://user-images.githubusercontent.com/4216599/34907158-09f36472-f859-11e7-8f04-3613e3f232f9.png)

And this is the output when minification is turned off
![image](https://user-images.githubusercontent.com/4216599/34907199-96be656e-f859-11e7-8ae6-e0db3a396a8a.png)

**Comment by mattiascaricato** [comment]
I've also tried turning on/off the `transpileTemplateLiterals` option but that's not the problem.

**Comment by philpl** [comment]
It seems that after the “font” properties and the interpolation value, the semicolons are missing. It might be that stylis is not interpreting this correctly.

Have you tried adding some extra ones there?

**Comment by mattiascaricato** [comment]
Thanks for the prompt response @philpl. I fixed all the CSS with the help of https://www.styled-components.com/docs/tooling#stylelint and now it's working
