### ISSUE TITLE
Classnames beginning with hyphens

### ISSUE THREAD

**Issue by joetidee** [styled-components/babel-plugin-styled-components#119]
I have just installed v1.4.0 and noticed that some of the classnames generated in my Jest snapshots begin with hyphens - this is the first time I have seen this. Is this correct?

Here is an example of the output:
`<strong classname="c7 -strong c8">`

**Comment by philpl** [comment]
Can you file an issue at jest-styled-components? I’m not quite familiar with how their reformatting works 

cc @MicheleBertoli

**Comment by MicheleBertoli** [comment]
This is interesting, thanks @joetidee @philpl.
Please [open an issue](https://github.com/styled-components/jest-styled-components/issues/new) in the `jest-styled-components` repo with a minimal repro example, and I'll be more than happy to help.

**Comment by philpl** [comment]
@joetidee I'll close this for now as I believe it's not related to the babel plugin, but Jest / jest-styled-components. Feel free to ping us here instead if you believe otherwise :+1:
