### ISSUE TITLE
Component names in production...

### ISSUE THREAD

**Issue by joetidee** [styled-components/babel-plugin-styled-components#121]
When installing this as a dev dependency, I would have expected the component names to just appear when running in dev environment. But they are also appearing in our production environment - how is this possible?

**Comment by mxstbr** [comment]
> When installing this as a dev dependency

That has nothing to with where you put your dependencies, but where you put it in your Babel config. You want to use the [Babel env option](https://babeljs.io/docs/usage/babelrc/#env-option) to  include the plugin in development with the `displayName` option set, and in production with it unset.

**Comment by kachkaev** [comment]
@joetidee (and others who are here from search), here is how I solved this issue in my next.js app

`.babelrc`

```js
{
  "presets": ["next/babel", "@zeit/next-typescript/babel"],
  "plugins": [
    [
      "babel-plugin-styled-components",
      { "ssr": true, "displayName": true, "preprocess": false }
    ]
  ],
  "env": {
    "production": {
      "plugins": [
        [
          "babel-plugin-styled-components",
          { "ssr": true, "displayName": false, "preprocess": false }
        ]
      ]
    }
  }
}
```

Correct me if I'm wrong folks 😉
