### ISSUE TITLE
Option to remove file from component's displayName

### ISSUE THREAD

**Issue by lcsrinaldi** [styled-components/babel-plugin-styled-components#123]
Hello! At the project that I'm currently working on we use the following structure for our components:

```
Component/
- index.js
- index.spec.js
- index.story.js
- index.styled.js -- this is where all the styled components related to the component live.
```

So far so good, this is still working like a charm. The problem is, when I use this plugin to rename all my components to a better `displayName` it takes into account the file name where the component is located, e.g.:

```
<indexstyled__DropdownContainer innerRef={[Function]}>
    <indexstyled__DropdownIcon onClick={[Function]} open={false} />
</indexstyled__DropdownContainer>
```

My question is, would be possible to remove this `indexstyled__` from the component name?

Thanks :)

**Comment by xinkule** [comment]
see issue #130

**Comment by probablyup** [comment]
Going to close this, as it's a dup of #130. We likely won't remove this feature, as it's needed to ensure there's enough information for stable and unique class names.
