### ISSUE TITLE
Desugar styled.tag to styled('tag')

### ISSUE THREAD

**Issue by probablyup** [styled-components/babel-plugin-styled-components#125]
This change will allow us to save some bundle size in styled-components and also be more futureproof, while allowing people to use the familiar syntax as desired.

**Comment by philpl** [comment]
However, this will worsen the experience for CRA users as long as Babel-macros aren’t released :(

**Comment by mxstbr** [comment]
How so? It would still work out of the box, the Babel plugin would replace the imports with ` from 'styled-components/no-tag-list'`. So if you're not using the Babel plugin it'll work and with the Babel plugin it'll just be smaller.

**Comment by philpl** [comment]
@mxstbr Ah! Sorry, I misunderstood it as working with Emotion’s strategy

**Comment by probablyup** [comment]
> However, this will worsen the experience for CRA users

I have no idea how CRA is so successful when you can't change anything without ejecting, TBH.

**Comment by mxstbr** [comment]
Todo:

- [x] Desugar
- [ ] Rewrite import (todo first: add that entry point to the main package)

**Comment by probablyup** [comment]
All the pieces are in place for this now
