### ISSUE TITLE
Upgrading from 1.4.0 to 1.5.0 makes webpack builds significantly slower

### ISSUE THREAD

**Issue by thomas88** [styled-components/babel-plugin-styled-components#126]
After upgrading from 1.4.0 to 1.5.0 our webpack build time increased from ~30sec to ~130sec. We're using styled-components 2.4.0 and I've also checked with styled-components 3.1.0. Any hints appreciated.

**Comment by probablyup** [comment]
Fascinating! Out of curiosity, are you using the parallel mode in the
webpack uglify plugin?

I’m guessing the addition of all the “pure” comments is making uglify keep
track of far more state and slowing down that stage of the process.

**Comment by thomas88** [comment]
@probablyup Not that I would no of. We're based on `react-boilerplate` and our webpack config is looking very similar to the one here https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js.

**Comment by mxstbr** [comment]
That is indeed very very curious. Can you try and see what happens when you disable the `uglifyPure` option to both the resulting bundle size and the build time?

```JSON
"plugins": [["styled-components", { "uglifyPure": false }]]
```

**Comment by thomas88** [comment]
Of course, please see the outcome in following table. In short: `"uglifyPure": false` prevents the long build times.

|version|`yarn start` initial build|`yarn run build` duration|`yarn run build` size for main.js|
|-|-|-|-|
|`1.4.0`|39151ms|145.13s|5.02 MB|
|`1.5.0`|126282ms|228.53s|5.02 MB|
|`1.5.0` with `"uglifyPure": false`|32758ms|139.10s|5.02 MB|

Let me know if I can check anything else.

**Comment by probablyup** [comment]
Thanks @thomas88, this was very helpful.

@mxstbr and @philpl I'm seeing this in my builds as well. I think we should switch this to off by default or remove it entirely, since it's seemingly not having the effect we want.

**Comment by mxstbr** [comment]
That's very unfortunate, so something's wrong. We'll need to investigate Uglify logs I guess?

**Comment by thomas88** [comment]
I'm not sure we're even using Uglify, since we don't have a reference to `UglifyJsPlugin` in our webpack config.

I've tried adding Uglify to webpack with `new webpack.optimize.UglifyJsPlugin(...)`, but there's no option regarding log output other than turning warnings on. Can you point me in a direction where I'd find mentioned log files?

**Comment by AndersDJohnson** [comment]
Related to https://github.com/styled-components/babel-plugin-styled-components/issues/114.

**Comment by csvan** [comment]
Confirming this, moving from 1.3 to 1.5 caused our webpack build times to increase by over 60%. This also affects our Jest config where tests are now running slower by the same factor.

**Comment by probablyup** [comment]
I'm also not seeing any bundle size reduction from having the comments... thinking we should just disable or remove the functionality.

**Comment by kitten** [comment]
@probablyup @mxstbr I recently noticed that this feature significantly slows down React Native builds too. I'm not sure what the effects of the comment might have on a typical build, but it was a shocking slowdown of over 5x. It might've been a bug elsewhere, but I don't think this is a coincidence.

Shall we disable this option by default?

**Comment by probablyup** [comment]
Released as 1.5.1 on NPM.

**Comment by tpucci** [comment]
Hi ! I added the plugin in a React Native project. Build time increased by +50% as well. And our jest test are stuck on `RUN`. It seems that it is a related issue. Do you hhave any recommendation on how to investigate on RN ?

**Comment by probablyup** [comment]
@tpucci are you using 1.6 of the plugin?
