### ISSUE TITLE
Doesn't seem to minify injectGlobal

### ISSUE THREAD

**Issue by asafigan** [styled-components/babel-plugin-styled-components#127]
I inject some global styles so that I don't have to configure css in webpack. One on the sylesheets I inject is normalize.css which has a lot of comments in it. When I view my bundle all of those comments are kept. I think injectGlobal isn't being optimized.

**Comment by mxstbr** [comment]
That's because it ships with a legal disclaimer which shouldn't be removed. See https://github.com/styled-components/styled-components/issues/1249 and #100.

**Comment by asafigan** [comment]
thanks for the quick response
