### ISSUE TITLE
displayName is prefixed with filename

### ISSUE THREAD

**Issue by jony89** [styled-components/babel-plugin-styled-components#130]
Why does the displayName of component includes the `blockName`/`filename` ? 

This makes it impossible to test the components using enzyme, when I try to `.find("ComponentName")` it fails because the component displayName is `filename__ComponentName`

Here is the relevant code : 

https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/displayNameAndId.js#L34-L46

(Edited by @kitten to show link to source instead of transpiled code sample)

**Comment by jony89** [comment]
fixed by adding `"fileName": false` to the plugin.

Yet, I could not find any docs regard this, in addition I think that `"fileName": false` should be the default.

```js
["babel-plugin-styled-components", { "displayName": true, "fileName": false }],
```

**Comment by kitten** [comment]
@jony89 This is entirely on purpose. The intention is to make the name of the component import-order-independent and to give it a name that is as unique as possible.

The reason for that is that it's quite common to give single-use StyledComponents similar names across files, e.g. `Item` in `components/List.js` or `Image` in `components/Avatar.js`.

So this way the name will end up being more identifiable. 

But maybe it'd indeed be great if we could document the `fileName` option? https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/utils/options.js#L7

**Comment by jony89** [comment]
Yeah, docs will be gr8, make sure to write something about testing with enzyme.

`So this way the name will end up being more identifiable`

identifiable at what point?

for errors - we have stack trace
for testing (with enzyme) - we must use `"fileName": false`

**Comment by kitten** [comment]
@jony89 I don’t understand why you must set it to false, but it’s mainly for inspecting elements while nothing is going wrong per se, in the sense of errors.

PRs to the website repo for docs are very welcome :)

**Comment by jony89** [comment]
> "I don’t understand why you must set it to false"

I mus set it to false in order to test the components using enzyme, when I try to .find("ComponentName") it fails because the component displayName is filename__ComponentName

I would love to cr8 a PR as long u agree with me.

**Comment by kitten** [comment]
@jony89 You can just use `.find(Component)` directly which should always work :)

Reference: https://github.com/airbnb/enzyme/blob/master/docs/api/selector.md#3-a-react-component-constructor

**Comment by probablyup** [comment]
@jony89 you can set `displayName: false` in the babel plugin option if you don't want noise.

**Comment by jony89** [comment]
@probablyup that will remove the displayName, which is needed.

**Comment by probablyup** [comment]
Not if you use the syntax Phil suggested.

**Comment by jony89** [comment]
@probablyup I hope someone will approve the PR, it's all written there : 

https://github.com/styled-components/styled-components-website/pull/240/files
