### ISSUE TITLE
Invalid class name being generated (first character is number) causing styles to fail

### ISSUE THREAD

**Issue by seankoji** [styled-components/babel-plugin-styled-components#138]
It appears babel-plugin-styled-components is assigning component classnames based on folder/file path structure. For example I have a component

```
/14-offer-radbtn/index.js
```

that file contains a component

```
const HoverIndicator = styled.span`
    opacity: 0;
`;
const StyledLink = const StyledLink = styled.a`
    &:hover {
        ${HoverIndicator} {
            opacity: 1;
        }
    }
`;

const BA14OfferRadbtn = () => (
    <StyledLink>
        <HoverIndicator />
    </StyledLink>
);

export default BA14OfferRadbtn;
```

However the hover effect doesn't work. On closer inspection, it appears that the generated class name is invalid as it starts with a number and is being ignored by the browser
![image](https://user-images.githubusercontent.com/13824565/39796343-54f4d8a2-5399-11e8-8133-63ed82a1f517.png)

generated CSS rule: 
![image](https://user-images.githubusercontent.com/13824565/39796418-affa8e36-5399-11e8-97ea-c5f3d0d093b8.png)

It appears that the class name is generated by looking at the folder path of the file. As the containing folder begins with "14" the class name follows suit invalidly. 

## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
 - Memory: 361.34 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
 - npm: 5.8.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.5.0 => 1.5.1
 - styled-components: ^3.2.3 => 3.2.6

## Expected Behavior
Valid CSS class name generated. 

## Actual Behavior
Invalid CSS classname generated, starting with a number, which is ignored by the browser

**Comment by probablyup** [comment]
Hmm it seems we do have some code that handles this: https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/displayNameAndId.js#L100

Maybe it's not being applied in all situations?

**Comment by seankoji** [comment]
Hmm I've tried turning the SSR option on and off with no joy. 

My setup is using `"@storybook/react": "^3.2.18"` with a custom `.babelrc` as follows

```
{
    "presets": ["env", "react"],
    "plugins": [
        "transform-class-properties",
        "transform-object-rest-spread",
        "styled-components",
        "macros",
        ["transform-runtime", {"polyfill": false,"regenerator": true}]
    ]
}
```

**Comment by probablyup** [comment]
Give `displayName: false` a try for the moment.

**Comment by seankoji** [comment]
Oh that works. 

> ["styled-components", {"displayName": false}],

But at the expense of the obfuscated names 

![image](https://user-images.githubusercontent.com/13824565/39797264-847a61c8-539e-11e8-8e99-01910172c026.png)

**Comment by probablyup** [comment]
Yup. I'm looking into a fix for this issue in the meantime.
