### ISSUE TITLE
Support babel-plugin-macros

### ISSUE THREAD

**Issue by ChristianMurphy** [styled-components/babel-plugin-styled-components#142]
Follow up to #59 

Create React App 2 is adding support for babel plugins through `babel-plugin-macros` https://github.com/facebook/create-react-app/pull/3675
Adding support for `babel-plugin-macros` would allow usage without ejecting or rewriting create react app.

documentation for creating a macro: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md

**Comment by probablyup** [comment]
Closing as this is being implemented in the core library: https://github.com/styled-components/styled-components/pull/2032
