### ISSUE TITLE
Rehydration bug

### ISSUE THREAD

**Issue by mquandalle** [styled-components/babel-plugin-styled-components#143]
I'm using this plugin with the `ssr` option turned to `true` which is supposed to generate unique identifiers for React components to avoid issues during re-hydration in case the two render trees doesn't match perfectly.

However I'm observing inconsistent rendering with the wrong child being in the wrong parent component.

You can see a minimal reproduction of this issue here: https://github.com/mquandalle/repro-gatsby-issue-5993

**Comment by probablyup** [comment]
Well it's going to render as the "else" of the ternary because `isMobileLayout` will always be false on the server. Then rehydration should kick in and replace it since client side knows about that thing.

Generally speaking, it's better to not have this sort of code or only do the switch on `componentDidMount`, because the recommended way of doing isomorphic React views is server and client should render the exact same thing prior to mount.

**Comment by mquandalle** [comment]
Wow you were super fast to answer, thank you so much! I updated the code 1 min after publishing this issue (it's the same but a bit more explicit about the issue).

The goal is indeed to have a SSR version that is a bit different than the first client render, which I understand isn't the best practice, but can happen on real-world occasions (for instance when we want to display different components depending on the screen size). A switch as in the reproduction works without styled-component: the page is first rendered using the SSR version and quickly after there is a small flash to replace it with the client-side version.

The problem with the styled-component version is that the resulting DOM is inconsistent with the React component (wrong component hierarchy), a problem I thought the `componentId` generated by the `ssr: true` option of this plugin was mean to avoid.

**Comment by probablyup** [comment]
> a problem I thought the componentId generated by the ssr: true option of this plugin was mean to avoid

Oh nope, separate things. The consistent `componentId` is specifically just making sure the same component definition has a consistent className hash between client and server. It doesn't have anything to do with changing out what component you are rendering.

One thing that occurred to me is if the underlying HTML element (e.g. `<div>`) is the same, I don't think React will do a full replacement on rehydration. It just warns that the classes are different.

To force React to behave, you could try using an alternate base tag in this edge case like `<span>` etc to force a re-render.

**Comment by mquandalle** [comment]
Yes I tried using different tags and it works in minimal examples, but in practice the issue is that as soon as there is a `<div>` in the page, the reconciler is going to re-use the SSR version and break the layout.

**Comment by probablyup** [comment]
@mquandalle late followup but it looks like gatsby didn't have the ssr option turned on for certain rendering phases, which may have contributed to this issue: https://github.com/gatsbyjs/gatsby/pull/7912
