### ISSUE TITLE
using babel-plugin-styled-components without ejecting from create-react-app

### ISSUE THREAD

**Issue by Oreville** [styled-components/babel-plugin-styled-components#148]
I'm using create-react-app and I would like to be able to use the babel-plugin-styled-components.

I've been looking for a way of doing this without having to eject, is this possible?

**Comment by maamounapprise** [comment]
Possible duplicate

https://github.com/styled-components/babel-plugin-styled-components/issues/59

**Comment by mxstbr** [comment]
Yeah you gotta use react-app-rewired with react-app-rewire-styled-components!
