### ISSUE TITLE
React SSR + External library containing styled-components

### ISSUE THREAD

**Issue by Lyncee59** [styled-components/babel-plugin-styled-components#149]
Hello everyone,

I am experiencing some issues and after searching for the last week to find a workaround, I finally decided to post my problem here !

My context is the following:
- Nextjs 6.1.1-canary3 (webpack 4 upgrade / babel 7.0)
- styled-components 3.4.0
- components: an external library I am developing exposing React components based on styled-components
(Note that I am using ESM to benefits from webpack 4 tree shaking)
- babel-plugin-styled-components 1.5.1 with ssr: true

In my consumer project, I am heavily relying on ```const MyCustomComponent = styled(MyComponent)``` as my library of component is exposing React components, no pure styled-components, and I can't use `.extend`

The project seems to work fine (as far as I tried) if the *components* library is published and restored as an external npm package.

However, in development mode, I am using `npm link` to link my components library with my consumer project, and then I start having problems with the inline style not being injected in the right order. 

Note that this style order issue does not happen when I don't use babel-plugin-styled-components but I then get the classes client/server mistmatch otherwise. 

Any idea ?

**Comment by probablyup** [comment]
One common issue with `npm link` is the library gets duplicated in the development bundles. That would definitely lead to all sorts of weird issues since there isn't meant to be more than one copy of styled-components loaded at a time. You can use aliasing to get around this by forcing webpack to always load your local project's version of s-c.

https://github.com/styled-components/styled-components/issues/1770#issuecomment-394101268

**Comment by damassi** [comment]
> You can use aliasing to get around this by forcing webpack to always load your local project's version of s-c.

During the server-side render pass this often isn't an option.

**Comment by eav** [comment]
having the same issue with ssr, agreed unfortunately it has nothing to do with webpack here

**Comment by damassi** [comment]
Related https://github.com/styled-components/styled-components/issues/2322
