### ISSUE TITLE
`jest --coverage` causes display name to change

### ISSUE THREAD

**Issue by IanEdington** [styled-components/babel-plugin-styled-components#151]
I get different display names for this component depending on if I run jest with `--coverage` or not.

```
const IconCircle = styled(Circle)`
  justify-content: center;
```

with `yarn jest --env=jsdom` I get `ReportIssueModal__IconCircle`  
with `yarn jest --env=jsdom --coverage` I get `Styled(Circle)`

![screen shot 2018-08-14 at 8 32 26 am](https://user-images.githubusercontent.com/6425087/44097687-59953fd2-9fac-11e8-8f58-da8ff707d44c.jpg)

**Comment by IanEdington** [comment]
I found a temporary solution by setting the displayName manually.

```
IconCircle.displayName = 'IconCircle';
```

**Comment by probablyup** [comment]
Hmm. So this happens because of the instrumentation babel is adding, which
changes the line order of the files and then consequently the component
hashes.

Do you have SSR mode on for the plugin? That might help.

**Comment by IanEdington** [comment]
Interesting. Thanks for explaining that.  enabling SSR mode on the styled-components babel plugin doesn't seem to have an effect. This is what I'm using:

**Comment by probablyup** [comment]
Okay, one other idea: for babel environment “test” (what jest uses) set the
plugin option displayName: false. I think this might help counteract what
Istanbul (the instrumentor) is doing.

**Comment by IanEdington** [comment]
Thanks for following up

Yes I did. Instead of `ReportIssueModal_IconCircle` I get `styled.div` which is unfortunately not very useful for a snapshot test. It does remove the conflict between the two environments though.

**Comment by probablyup** [comment]
I mean I wouldn’t really rely on snapshot tests for this sort of thing
anyway to be honest. The way the components are named are not part of the
public API, so they could change at any time.

**Comment by ljharb** [comment]
To be clear, the way components are named is absolutely a part of the public API - the API is everything observable - so changing them must follow semver just like anything else.
