### ISSUE TITLE
v1.6.0 seems to break babeling styled-component's own code

### ISSUE THREAD

**Issue by robin-drexler** [styled-components/babel-plugin-styled-components#158]
Hey, everyone
First of all, thanks for all the amazing work you do! :)

We have recently upgraded to version`^1.6.0` of `babel-plugin-styled-components` , when we started to see the following error:

```
TypeError: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "CallExpression"
    at Object.validate (/Users/robin.drexler/Development/babel-styled/node_modules/@babel/types/lib/definitions/utils.js:128:13)
    at Object.validate (/Users/robin.drexler/Development/babel-styled/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at NodePath._replaceWith (/Users/robin.drexler/Development/babel-styled/node_modules/@babel/traverse/lib/path/replacement.js:194:9)
    at NodePath.replaceWith (/Users/robin.drexler/Development/babel-styled/node_modules/@babel/traverse/lib/path/replacement.js:178:8)
    at /Users/robin.drexler/Development/babel-styled/node_modules/babel-plugin-styled-components/lib/visitors/desugarStyled.js:37:14
    at PluginPass.MemberExpression (/Users/robin.drexler/Development/babel-styled/node_modules/babel-plugin-styled-components/lib/index.js:16:40)
    at newFn (/Users/robin.drexler/Development/babel-styled/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/robin.drexler/Development/babel-styled/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/robin.drexler/Development/babel-styled/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/robin.drexler/Development/babel-styled/node_modules/@babel/traverse/lib/path/context.js:88:12)
```

We dug into it a bit and found that it seems to be caused by [desugarStyled.js](https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/desugarStyled.js#L27) as it tries to transpile [styled.js](https://github.com/styled-components/styled-components/blob/8102cca24a97a89ed1444283d1e5e4c410c9e5c2/src/constructors/styled.js#L10) in `styled-components` which then fails. 

We also noticed a significant slowdown when the new plugin version is used. We uncommented the [MemberExpression visitor](https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/index.js#L14) and it got a lot faster again.

We have created a small repository where you can reproduce the issues described.
In this repository, we have put a file `input.js` which inlcudes the esm version of styled-components and `nostyled.js` that has the same content but with the line removed which causes the error.

https://github.com/robin-drexler/styled-components-babel-issue
 
```
git clone  git@github.com:robin-drexler/styled-components-babel-issue.git
cd styled-components-babel-issue
yarn
```

You can run `yarn broken` to see the error.
`yarn slow` to get a successful but slower result.
`yarn fast` which removes  `babel-plugin-styled-components` and is faster.

I used node v10.3.0 and yarn 1.7.0
Let me know if there is more info to provide. :)

**Comment by probablyup** [comment]
Hmm thank you. I'll take a look today or tomorrow

**Comment by probablyup** [comment]
@robin-drexler pushed a fix for the hard error in 1.6.1. Not sure about the slowdown though... perhaps it's due to the SSR option being on by default now? You can disable it by passing `"ssr": false` to the plugin.

**Comment by robin-drexler** [comment]
@probablyup Thanks for the timely fix! 

Regarding the slowdown: Setting `ssr` to `true` or `false` does not seem to make any difference. It's always about 9 seconds on my machine.

Removing the [`MemberExpression`](https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/index.js#L14) reduces the time to 0.7 seconds.

**Comment by rroslaniec** [comment]
With 1.6.x version I've got on node error during the build:
```
function _templateObject5(){var data=_taggedTemplateLiteral(["\n      @media screen and (max-width: 360px) {\n        ",";\n      }\n    "]);_templateObject5=function _templateObject5(){return data;};return data;}function _templateObject4(){var data=_taggedTemplateLiteral(["\n      @media screen and (max-width: 540px) {\n        ",";\n      }\n    "]);_templateObject4=function _templateObject4(){return data;};return data;}function _templateObject3(){var data=_taggedTemplateLiteral(["\n      @media screen and (max-width: 767px) {\n        ",";\n      }\n    "]);_templateObject3=function _templateObject3(){return data;};return data;}function _templateObject2(){var data=_taggedTemplateLiteral(["\n      @media screen and (max-width: 1536px) {\n        ",";\n      }\n    "]);_templateObject2=function _templateObject2(){return data;};return data;}function _templateObject(){var data=_taggedTemplateLiteral(["\n      @media all and (-ms-high-cont

TypeError: styled_components__WEBPACK_IMPORTED_MODULE_0__ is not a function

```
