### ISSUE TITLE
Update to new syntax

### ISSUE THREAD

**Issue by mxstbr** [styled-components/babel-plugin-styled-components#16]
As of https://github.com/styled-components/styled-components/pull/227 the new syntax for the private API is `.withConfig`:

```JS
const Box = styled.div.withConfig({ displayName: 'Box', componentId: 'Button_asdf123' })`
  styles: here;
`
```

*This avoids issues on ReactNative where `target` would before need to be `View` (no string) and we'd need to import it, which would've made everything much more compilcated.*

I'm thinking about switching this to be `.__config` to make sure people don't accidentally use it, but that's a trivial change. We should get this changed asap!

**Comment by vdanchenkov** [comment]
How does it work with component wrapping? This way?
```jsx
const StyledBox = styled(Box).withConfig({ displayName: 'StyledBox', componentId: 'Button_asdf123' })`
  styles: here;
`
```

**Comment by mxstbr** [comment]
To elaborate a bit on why this is a necessary change, on the web we can transpile our `styled` calls like so:

```JS
// before
const Box = styled.div``
```

```JS
// after
const Box = styled({ target: 'div' })``
```

Which is what we do right now! The issue is, that doesn't work on ReactNative. Imagine this:

```JS
// before
const Box = styled.View``
```

Transpiling it to this breaks, because in ReactNative there are no string primitives:

```JS
// after
const Box = styled({ target: 'View' })`` // 🚫 Breaks
```

Instead, we'd have to transpile it to this:

```JS
// after
import { View } from 'react-native'
const Box = styled({ target: View })``
```

Which would have been a pain to do!

So, with the new syntax we fully avoid this issue, because no matter what the user does this always works:

```JS
const Box = styled.div.withConfig({ })`` // That works perfectly fine
const Box = styled.View.withConfig({ })`` // That works too, no import needed!
const Box = styled(OtherComp).withConfig({ })`` // No problem
const Box = styled('div').withConfig({ })`` // No problem either
```

Does that explain better why we need to switch?

**Comment by vdanchenkov** [comment]
@mxstbr Thanks for the explanation. I'll update it in a nearest time.
