### ISSUE TITLE
Add @babel/helper-annotate-as-pure to dependencies

### ISSUE THREAD

**Issue by acrazing** [styled-components/babel-plugin-styled-components#164]
This is used but not installed: https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/pure.js#L1

**Comment by probablyup** [comment]
Ah must have put it in devDeps. Can you send a PR?

**Comment by probablyup** [comment]
Oh so weird. I wonder how that got through...

**Comment by probablyup** [comment]
should be fixed in 1.7.1
