### ISSUE TITLE
My jenkin build is failing ,please help me in that

### ISSUE THREAD

**Issue by cpratiksha** [styled-components/babel-plugin-styled-components#165]
/src/index.js
Module build failed: Error: Cannot find module 'babel-plugin-styled-components' (While processing preset: "/Users/Shared/Jenkins/Home/workspace/project-dev/node_modules/babel-preset-react-app/index.js")
    at Array.map (<anonymous>)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by cpratiksha** [comment]
What is the solution? I installed this library via npm 

> sudo npm install --save-dev babel-plugin-styled-components


Still coming to this error, not getting any working solution.

**Comment by probablyup** [comment]
Yeah the issue is the react-app preset does local resolution of babel components and the styled-components babel plugin is installed at the top of your node_modules tree, so I don't think it'll find it.

That's why the rewired thing exists.

**Comment by cpratiksha** [comment]
> Yeah the issue is the react-app preset does local resolution of babel components and the styled-components babel plugin is installed at the top of your node_modules tree, so I don't think it'll find it.
> 
> That's why the rewired thing exists.

OK, Thank you, Evan, for the quick reply. I try with your solution.

**Comment by cpratiksha** [comment]
while installing this dependency node sass error occurs.

npm install --save react-app-rewire-styled-components
.
.
.
.
node-sass@4.8.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by probablyup** [comment]
No idea, we don't use node-sass in any styled-components library.

**Comment by JimTheMan** [comment]
I am also getting the error, "Error: Unable to find plugin "babel-plugin-styled-components". Perhaps you need to install its package?" after running npm i and adding it to .babelrc....

I tried `npm install --save react-app-rewire-styled-components` but it did not help at all.

@probablyup is there any solution for this???
