### ISSUE TITLE
Struggling to get plugin working–transforms aren't being applied?

### ISSUE THREAD

**Issue by Vpr99** [styled-components/babel-plugin-styled-components#166]
Hi all,

I'm trying to get the plugin working _at all_ and I'm at my wits end here. As far as I can tell, no transformations are happening. I'm using Gatsby, but just in development mode and with a custom babel config:

`babel.config.js`:
```jsx
module.exports = {
  presets: ['@babel/preset-env', '@babel/react'],
  plugins: [
    'babel-plugin-styled-components',
    '@babel/plugin-proposal-class-properties',
  ],
};
```

and my `package.json`:
```json
"devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-plugin-styled-components": "^1.7.1",
    ...
}
```

Currently, when I go to React devtools, I'm still getting tons of <styled.xxx> elements, instead of displayNames and in Chrome inspector, my classes on a component look like this: `class="sc-ifAKCX fjeiAi"`

Any help would be greatly appreciated—I'm really stuck.

**Comment by probablyup** [comment]
I think you need to use the gatsby plugin? https://www.gatsbyjs.org/packages/gatsby-plugin-styled-components/

**Comment by Vpr99** [comment]
Thanks for the thought @probablyup—no dice though :/

I think the Gatsby plugin only applies if you're using their built-in babelrc file. I just tried adding a `displayName` manually to a couple of my styled components and that works a-okay, but the plugin still isn't doing anything. Would it be helpful for me to see if I can reproduce in a demo repo?

**Comment by probablyup** [comment]
I mean I'd probably post in one of the issues on their repo or try asking on their [Spectrum](https://spectrum.chat/gatsby-js). When it comes to third party integrations the knowledge is a bit scattered.

**Comment by Vpr99** [comment]
@probablyup PROGRESS! So I created a sample repo and encountered the same problem with just a vanilla React/Webpack build. Here's what the problem is:

I'm using the function syntax (added in [3.4.0](https://github.com/styled-components/styled-components/releases/tag/v3.4.0)), so my styled components look like this:

```jsx
const myComponent = styled.div({
    // blah
});
```

That isn't picked up by the plugin, whereas this does:

```jsx
const myComponent = styled.div`
    // blah
`;
```

Thoughts?

**Comment by Vpr99** [comment]
No problem! I'll probably need some help, but I'll see if I can take a stab at it first :)

**Comment by Vpr99** [comment]
@probablyup yep, I got super stuck—might be best if you did it. Basically where I got to (baby steps) was:

We need to add a visitor for `CallExpression` as well as `TaggedTemplateExpression`. Then, `isStyled` needs to be modified to accept the call expression (`path.node`?) as well as `path.node.tag`. 

Was I at least on the right track?

**Comment by probablyup** [comment]
@Vpr99 want to test `babel-plugin-styled-components@dev` and let me know if it works?

**Comment by Vpr99** [comment]
@probablyup almost working! Now we've got:

`const foo = styled('div')({  })`

but this one isn't working still:

`const foo = styled('div')(props => ({  }))`


Thanks for all your hard work on this :)

**Comment by probablyup** [comment]
@Vpr99 try it one more time, latest from the "dev" tag

**Comment by Vpr99** [comment]
@probablyup works great!
