### ISSUE TITLE
Use with pre-eject create-react-app@2.0

### ISSUE THREAD

**Issue by spilist** [styled-components/babel-plugin-styled-components#168]
Since [create-react-app@2.0.3](https://github.com/facebook/create-react-app/releases/tag/v2.0.3) is just released with [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros) support, is it possible to use this plugin with the macro? (Or planning to?)

My team want to use this plugin without ejecting CRA@2.0, and currently [react-app-rewired](https://github.com/timarney/react-app-rewired) doesn't support the version.

**Comment by probablyup** [comment]
There’s a PR open against styled-components core for this if you want to
follow along

**Comment by probablyup** [comment]
https://github.com/styled-components/styled-components/pull/2032

**Comment by spilist** [comment]
Thanks @probablyup , I didn't know of it!
