### ISSUE TITLE
[SOLVED]Problems on styled-components v1.1.2 -> Not compatible

### ISSUE THREAD

**Issue by yessinekebir** [styled-components/babel-plugin-styled-components#169]
Hi , i've installed the plugin on a 1.1.2v of styled component , but it's not compatible ,problem is that style change on my app.
Is there a solution for using babel-plugin-styled-components in 1.1.2 styled-component library?

**Comment by mxstbr** [comment]
Upgrade to the latest version of styled-components? What's keeping you on v1.1.2?

**Comment by yessinekebir** [comment]
@mxstbr  Thanks for answer. 
Problem it's a big project made with styled-components 1.1.2, and when i update to the last version lot of styles pages change.

**Comment by mxstbr** [comment]
Can you try updating to v2?

**Comment by yessinekebir** [comment]
**Same problem using this versions:**  
  "styled-components": "^2.4.1",
    "babel-plugin-styled-components": "^1.8.0",

**Comment by mxstbr** [comment]
I'm afraid you'll have to upgrade to v3 or later for this plugin to work 😕

**Comment by yessinekebir** [comment]
Updating to v3.4.6 same problem.. 
Do you know what's the main devDependencies that change styles ? (Difference between 1.1.2 and 3.4.6).
Thanks.

**Comment by yessinekebir** [comment]
I've reinstalled babel-plugin with styled-components 1.1.2 and problem changed.. Now i've in console: 
Dynamic page loading failed TypeError: styled_components__WEBPACK_IMPORTED_MODULE_0__.default.div.withConfig

**Comment by probablyup** [comment]
@yessinekebir I don't think the babel plugin was ever compatible with styled-components v1? Only v2+

**Comment by yessinekebir** [comment]
Solved.. 
Problem on v3.4.6 and babel-styled-component  v1.8 is the minified props..
By default the plugin pass minification: true, and it broke my CSS style.

**SOLUTION**
 ["babel-plugin-styled-components", {
      "minify": false
    }]

**Comment by probablyup** [comment]
If you could post some of your code we could possibly improve the minifier
