### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by kopax** [styled-components/babel-plugin-styled-components#18]
I wanted to minimize my css, as I have seen issues closed in react-boilerplate, I thought it was solved by this plugin.

I have tried to install using npm and git+ssh, I know it's written WIP but is there a way to test the minification or it's not ready at all ?

**Comment by mxstbr** [comment]
Not ready yet as it's only useable with v2 of styled-components, which we'll release at the beginning of January. Soooon!

**Comment by vdanchenkov** [comment]
@kopax 

For evaluation you can do
```ssh
git clone git@github.com:styled-components/babel-plugin-styled-components.git
cd babel-plugin-styled-components
npm link

cd you-project-directory
npm link babel-plugin-styled-components
```

You can use it with current version of styled components if you disable displayName and ssr, as thouse features are not implemented in master branch of styled components yet. 

Take a look at https://github.com/styled-components/babel-plugin-styled-components/tree/master/test/fixtures/09-minify-css-to-use-without-transpilation

**Comment by kopax** [comment]
@mxstbr , will you take care of styled-components v2 soon ? I will need at some point to compress the css with this, and the sooner the better.

**Comment by mxstbr** [comment]
Yes, @geelen and I have set our eyes on a release sometime within the next weeks, probably at the beginning of February! Not much missing 😉

**Comment by kopax** [comment]
hi, Any update on this ?

**Comment by mxstbr** [comment]
Still working on it! 😊
