### ISSUE TITLE
`cssProp` feature does not transpile template literals

### ISSUE THREAD

**Issue by keesvanlierop** [styled-components/babel-plugin-styled-components#184]
I was trying out the new cssProp feature introduced in 1.9, but noticed that the components created by the plugin are not transpiled by @babel/preset-env. So now my client bundle includes template literals, which is something IE does not really like. I've tried to set transpileTemplateLiterals to true, but that didn't work out.

My babel config looks like this:

```javascript
{
    ...,
    "presets": [
        [
            '@babel/preset-env',
            { targets: { browsers: ['> 1%', 'last 2 versions', 'ie 11'] } }
        ],
        ...,
    ],
    plugins: [
        ['babel-plugin-styled-components'],
        ...,
    ]
}
```

**Example with CSS notation**
```jsx
<Card
    css={`
        max-width: 400px;
        border-top: 0;
    `}
/>
```

transpiles to:

```.....g=Object(a["c"])(i["a"])`
                        max-width: 400px;
                        border-top: 0;
                    `;n.d(t,"a"......```

**Example with object notation**:

```jsx
<Card
    css={{
        maxWidth: '400px',
        borderTop: 0,
    }}
/>
```

transpiles to:

```.....o.a.createElement(g,{theme:"light",_$p_:{maxWidth:400,borderTop:0}},t&&o.a.createElement(c.a,{p:!0},t),r))}}]),t}(),g=Object(a["c"])(i["a"])`${e=>e._$p_}`;```

I would expect that it transpiles into either object notation or a version compatible to the settings specified in the babel-env preset, but maybe I'm missing something here.

**Comment by mxstbr** [comment]
Great catch! @satya164 can we somehow run the css prop transform _before_ preset-env?

**Comment by satya164** [comment]
@mxstbr If I remember correctly, plugins always run before presets (and presets run last to first). so it should already be going through `preset-env`. Maybe we need to call `program.requeue()` when we're done.

**Comment by keesvanlierop** [comment]
@satya164 The following does not seem to change anything for me:

```javascript
Program: {
    enter(path, state) {
        state.required = false
        state.items = []
    },
    exit(path, state) {
        const oldLength = path.node.body.length;

        path.node.body.push(...items);;

        const newLength = path.node.body.length;

        for (let i = 0; i < newLength - oldLength; i++) {
            path.get('body')[oldLength + i].requeue();
        }
    },
},
```

Doesn't seem like the exit hook is called at all.

**Comment by satya164** [comment]
@keesvanlierop hmm the `styled` statements won't be inserted if it wasn't called. have tried putting console logs there to see if it's being called?

can you also try just doing `path.requeue()` after the push?

**Comment by satya164** [comment]
> I also had a plugin running that removes console logs
That shouldn't affect the Babel plugin 🤔
Are you checking your Terminal for the logs? They won't be in the browser console.

Can you put a `console.log` before `path.get('body')[oldLength + i]` and tell me what it gets called with? Also maybe you can create a small sample project? I'll try to debug it if I get few free minutes.

**Comment by keesvanlierop** [comment]
It did affect though. Once i removed `transform-remove-console`, the logs started showing in the terminal (but that's probably entirely another issue).

`console.log(newLength, oldLength)` => Sometimes are equal, sometimes they differ (probably as expected

`console.log(path.get('body')[oldLength + i])` => Returns a NodePath instance:

```
NodePath {
  parent:
   Node {
     type: 'Program',
     start: 0,
     end: 2962,
     loc:
      SourceLocation {
        start: Position { line: 1, column: 0 },
        end: Position { line: 96, column: 0 } },
     sourceType: 'module',
     interpreter: null,
     ... 
}
```
Not sure what info you need here, because it's quite a huge object :)

**Comment by satya164** [comment]
Hmm seems the items are pushed here, https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/transpileCssProp.js#L103

In that case, the Program visitors aren't doing anything

**Comment by satya164** [comment]
@keesvanlierop can you try this PR: https://github.com/styled-components/babel-plugin-styled-components/pull/185

seems to be working for me locally.

**Comment by keesvanlierop** [comment]
Can confirm. 

`path.requeue(path.get('body')[oldLength + i]);` is what did the trick for me.

**Comment by keesvanlierop** [comment]
Also identified the other issue, that was probably related to the `cacheDirectory` option that at that time still was set to `true`
