### ISSUE TITLE
Is css props release in 1.9.2

### ISSUE THREAD

**Issue by kopax** [styled-components/babel-plugin-styled-components#190]
Hi and sorry if it's already explained somewhere,

I was playing with the experimental plugin, and now there is a 1.9.2 but there is no changelog.

https://github.com/styled-components/babel-plugin-styled-components/releases

Is the 1.9.2 supposed to work with the `css` props?

**Comment by mxstbr** [comment]
Yep

**Comment by kopax** [comment]
Fair enough.  Thanks a lot. 

I see that you forced the usage of `css` for using keyframes, while we can use these keyframes outside of react (svg, html) but generate them with styled.

I believe this will be still possible what do you think?

**Comment by mxstbr** [comment]
Changelog is written!

> I see that you forced the usage of css for using keyframes, while we can use these keyframes outside of react (svg, html) but generate them with styled.

This is no longer possible with styled-components v4 to make lazy injection and code splitting of keyframes possible, so this also isn't possible with the macro.
