### ISSUE TITLE
`css` prop produces broken CSS when used with a plain string literal

### ISSUE THREAD

**Issue by slice** [styled-components/babel-plugin-styled-components#194]
Hello! :wave:

I noticed that with `babel-plugin-styled-components@1.9.3`, using strings with the `css` prop produces invalid CSS:

![image](https://user-images.githubusercontent.com/4206232/49782593-b761ca00-fccb-11e8-9ff2-f67df1cfb5e8.png)

This invalid CSS appears to be the same as the invalid CSS produced by the bug in issue #186.

Here is the JSX that causes the issue:

```jsx
      <div className="layout-container">
        <main>{children}</main>
        <footer css="color: #999">&copy; slice 2018</footer>
      </div>
```

On the other hand, when using template strings:

```jsx
      <div className="layout-container">
        <main>{children}</main>
        <footer
          css={`
            color: #999;
          `}
        >
          &copy; slice 2018
        </footer>
      </div>
```

or objects:

```jsx
      <div className="layout-container">
        <main>{children}</main>
        <footer css={{ color: '#999' }}>&copy; slice 2018</footer>
      </div>
```

It works fine! Plain strings don't work, though. It might have something to do with the curly braces -- they're omitted when using plain string literals, which *might* have something to do with the bug. 😄 Just a guess, though!

**Comment by mxstbr** [comment]
Is there a chance you could put the buggy code into a repo and push it up? That would really help me debug this :pray:

**Comment by mxstbr** [comment]
Can replicate with the code from #181, will try and investigate!

**Comment by slice** [comment]
Thank you! ❤️

Sorry about the minimal reproduction code, I was sleeping.

**Comment by mxstbr** [comment]
No worries :blush:
