### ISSUE TITLE
Support reusing CSS strings in the CSS prop

### ISSUE THREAD

**Issue by janosh** [styled-components/babel-plugin-styled-components#197]
It would be cool if the new [`css` prop](https://www.styled-components.com/docs/api#css-prop) supported passing in [css template literals](https://www.styled-components.com/docs/api#css).

Currently, I can only write a string explicitly into the prop field:
```jsx
<div
  css={`
    background: papayawhip;
    color: ${props => props.theme.colors.text};
  `}
/>
```
I cannot save it to a variable and reuse it in multiple places:

```jsx
const style = `
    background: papayawhip;
    color: ${props => props.theme.colors.text};
  `
<header css={style} />
<div css={style} />
```
And I cannot import it from other files or pass it as a prop from other components in the case of styles used in multiple places in a project. This is a stripped down example:
```jsx
// Parent.js
import { css } from 'styled-components'

import Child from './Child'

const styles = css`
  color: ${props => props.theme.blue};
`

export default () => (
  <Child styles={styles} />
)
```

```jsx
// Child.js

export default ({ styles }) => (
  <p css={styles}>Blue text</p>
)

**Comment by mxstbr** [comment]
In theory, this should already work with the way it's transformed, I'll dig into this soon.

**Comment by kopax** [comment]
I am using `css={css``}``and not `css={}`, every where in my code. I thought it was supposed to be like that. What is the `css` util for then?

**Comment by janosh** [comment]
Somehow this has been fixed in the meantime. I upgraded to `babel-plugin-styled-components` v1.10.0 and all of the above use cases are working now. Not sure if updating was what fixed it, though. Feel free to close this issue.

**Comment by mxstbr** [comment]
Awesome, happy to hear!
