### ISSUE TITLE
Disable displayName stuff in production

### ISSUE THREAD

**Issue by mxstbr** [styled-components/babel-plugin-styled-components#2]
We should check for `process.env.NODE_ENV !== 'development'` and disable `displayName` if that's the case.

**Comment by vdanchenkov** [comment]
The issue was created when we used IIFE and had no configuration flags.

These days, I'd recommend using https://babeljs.io/docs/usage/babelrc/#env-option to configure it explicitly.

@mxstbr  WDYT?

**Comment by mxstbr** [comment]
Sounds very reasonable!

**Comment by breadadams** [comment]
In case it helps anyone else, the updated babel URL would be: https://babeljs.io/docs/en/config-files#apienv

Here's an example of disabling `displayName` for production:

```
// .babelrc.js

module.exports = function (api) {
  return {
    plugins: [
      ["styled-components", { ssr: true, displayName: !api.env("production") }]
    ]
  };
};
```
