### ISSUE TITLE
Questions about componentId 

### ISSUE THREAD

**Issue by vdanchenkov** [styled-components/babel-plugin-styled-components#20]
Currently with `{ ssr: true, displaName: false }` component id gets generated with component name `Component-137hlza`. Should we change it to `s-137hlza` if displayName is disabled? I guess human-readable name here is solely for debug purposes?

**Comment by vdanchenkov** [comment]
I think, I see a problem with 3-rd party libs. 

You do not usually transpile code from node-modules, so I think 3-rd party libs built with styled-components should be preprocessed with this plugin to get componentId's in place before publishing.

But in that case id's from different libs will clash. If it's an actual problem, I have one solution on my mind. Plugin could determine package name of the current project and use it in the hash.

**Comment by mxstbr** [comment]
> Should we change it to s-137hlza if displayName is disabled?

Hmm, I guess?

> But in that case id's from different libs will clash. If it's an actual problem, I have one solution on my mind. Plugin could determine package name of the current project and use it in the hash.

That's a good point, I hadn't thought of that! /cc @geelen could that be an issue?
