### ISSUE TITLE
Did styled-components or babel-plugin-styled-components changed the way it inject the css in the page in production lately ? How can I see the generated css in a production build?

### ISSUE THREAD

**Issue by kopax** [styled-components/babel-plugin-styled-components#200]
Hi everyone, I can see a lot of change with the `css` props, and the plugin.

I am using in an application the required dependencies:

- create react app (just for creating the app)
- styled component
- babel-plugin-styled-components.

I noticed after doing `npm run build` and opening the production application in my browser that it is not possible anymore to get *(using the chrome developer tab)* the css rules in the page.

All I can see is `<style data-styled="" data-styled-version="4.1.3"></style>`

If I check a rules and click on the reference link, it brings to that element again.

Is there a way I can see the generated css? Thanks!

**Comment by mxstbr** [comment]
That was always the case and has nothing to do with the Babel plugin or the CSS prop.

In production mode we use a browser CSS injection API (`insertRule`) that is 10-100x faster than the naive injection API we use in development mode. Unfortunately, Chrome DevTools have a bug where they do not show styles in the HTML tree that are injected with this ultra fast injection API, so there's nothing we can do there except recommend you to use a different browser!

**Comment by kopax** [comment]
Thanks I understand now. May I ask what browser do you prefer over chrome?
