### ISSUE TITLE
Suggestion: Pass css prop to all children if component wraps render in React.Fragment

### ISSUE THREAD

**Issue by janosh** [styled-components/babel-plugin-styled-components#205]
If a component encloses its children in a `React.Fragment`, e.g.
```jsx
export const Page = ({title, body}) => (
  <>
    <h1>{title}</h1>
    <p>{body}</p>
  </>
)
```
applying the `css` prop to it will do nothing, i.e.
```jsx
<Page title="Hello" body="World" css={`color: blue;`} />
```
will not result in blue text. Would this functionality be undesirable in some cases or could it be added?

**Comment by mxstbr** [comment]
You need to use the passed-in `className`, no matter if its using a Fragment or any other kind of node:

```JS
export const Page = ({title, body, className}) => (
  <>
    <h1 className={className}>{title}</h1>
    <p>{body}</p>
  </>
)
```
