### ISSUE TITLE
Minification with & breaks CSS

### ISSUE THREAD

**Issue by wmertens** [styled-components/babel-plugin-styled-components#207]
Something like

```js
const SlickSlider = styled(OrigSlickSlider)`
	.slick-track {
		display: flex;
	}
	&.slick-slider {
		width: 100%;
	}
`
```

gets minified to

```
.slick-track{display:flex;}&.slick-slider{width: 100%;}
```

however, it seems that this disables the meaning of `&`. I assume the problem is that the CSS library wants whitespace before `&`?

**Comment by hilkeheremans** [comment]
(Fancy us bumping into each other here, @wmertens ...)

Experiencing the same issue, which is breaking some of our styling throughout or application.

**Comment by probablyup** [comment]
> I assume the problem is that the CSS library wants whitespace before &?

No, that shouldn't be it... I just tried writing a test for it in v5 and it replaced correctly. Not really sure what's going on here as the stringify code hasn't changed much between v4 and v5.

**Comment by probablyup** [comment]
I wrote a test in s-c core for this and couldn't reproduce the behavior you're describing in v4 or v5, going to close. Feel free to open a new issue with a reproduction sandbox if you're still experiencing the problem.
