### ISSUE TITLE
weird interaction with storybook 5 breaks compilation

### ISSUE THREAD

**Issue by cellog** [styled-components/babel-plugin-styled-components#212]
As referenced here: https://github.com/storybooks/storybook/issues/5882

Greenkeeper asked us to upgrade from 4.1 to 5.0 of storybook, and now, suddenly, we get failures where the styled components babel plugin is replacing imports with declarations:

```
ERROR in ./src/components/creator/lock/KeyList.js 13:15
Module parse failed: Unexpected keyword 'var' (13:15)
You may need an appropriate loader to handle this file type.
| import { connect } from 'react-redux';
| import styled from 'styled-components';
> import Link, { var _ref3 =
| /*#__PURE__*/
| React.createElement(Message, {
 @ ./src/stories/creator/KeyList.stories.js 5:0-64 37:29-36 49:29-36 61:29-36 73:29-36 85:29-36
 @ ./src/stories sync \.stories\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```

The PR that shows these errors is https://github.com/unlock-protocol/unlock/pull/1877

I have not yet tried to isolate this, would love some ideas of why this might be happening so I know what to isolate.

**Comment by probablyup** [comment]
Closing as it appears to be a storybook issue reading through the linked thread that is now closed.
