### ISSUE TITLE
styled.keyframes.withConfig is not a function

### ISSUE THREAD

**Issue by maeligg** [styled-components/babel-plugin-styled-components#213]
Hello,

Since adding this plugin on my project, I get the runtime error
```
TypeError: styled.keyframes.withConfig is not a function
```
I thought this may be related to https://github.com/styled-components/babel-plugin-styled-components/issues/36 but I experienced it with both versions 3.4.10 and 4.1.3 of styled component (I'm using 1.10.0 of the plugin). Note that this only seems to happen on *some* styled components as I have others that were processed and are displayed correctly on storybook.

**Comment by benhunt29** [comment]
I also am getting this error, I'm on `styled-components: 3.4.10` and `babel-plugin-styled-components: 1.10.0`

**Comment by probablyup** [comment]
keyframes is a named export, not a property of `styled`

```js
import styled, { keyframes } from 'styled-components
```

**Comment by maeligg** [comment]
Yes this is already what I'm using in my component :
```
import styled, { keyframes } from 'styled-components'

const rotate = keyframes`
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
`
```

This is bundled (wrongly ?) into the following :
`var rotate = styled.keyframes(['from{transform:rotate(0deg);}to{transform:rotate(360deg);}']);`
