### ISSUE TITLE
Styled-component example with Enzyme

### ISSUE THREAD

**Issue by juancafe4** [styled-components/babel-plugin-styled-components#214]
I am using displayName false and fileName false in my babel setup. But enzyme is not able to find any styled-component with a string as a parameter

`wrapper.find('Button')`

Thanks

**Comment by probablyup** [comment]
Please use the `enzymeFind` test util, thanks! https://www.styled-components.com/docs/api#enzymefind

**Comment by juancafe4** [comment]
it requires to import the component which I don't want this styled component is private

**Comment by juancafe4** [comment]
> Please use the `enzymeFind` test util, thanks! https://www.styled-components.com/docs/api#enzymefind
it requires to import the component which I don't want this styled component is private
