### ISSUE TITLE
css prop isn't working when used in another yarn workspace package

### ISSUE THREAD

**Issue by th0th** [styled-components/babel-plugin-styled-components#218]
Greetings,

I am having a strange behavior for `css` prop. Not sure if it is a bug or feature 😄 

I have a project with two packages (yarn workspaces) which has a structure like this,
```
- packages
  - common (package name: @app/common)
    - components
      - Component1.jsx <- export default styled.div
      - Component2.jsx
      - index.js <- exports all components from directory
   
  - web-app (package name: @app/web-app)
    - routes
      - Route.jsx
```

If I import `Component1` from `Route.jsx` with 

```
import {
  Component1,
} from '@app/common/components';
```

and use with `css="margin-top: 10px;"` it works.

But it doesn't do anything if I import from `Component2.jsx` with 

```
import Component1 from './Component1';
```

and use with the same `css` prop. Is there a directory scope definition or something for `css` prop?

**Note:** I have the following `.babelrc` in `packages/web-app` and not in `packages/common`.

```
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    "@babel/transform-runtime",
    "react-hot-loader/babel",
    "babel-plugin-styled-components"
  ]
}
```

After posting, I noticed class names aren't human readable when the component is from `@webapp/common` so I am guessing babel plugin isn't being utilized at all in `common` package.

**Comment by th0th** [comment]
Turns out the cause is the changes in configuration structure introduced with babel 7.

**Comment by dminkovsky** [comment]
> Turns out the cause is the changes in configuration structure introduced with babel 7.

Hi @th0th, do you remember how you fixed this? I am having the same issue.

**Comment by dminkovsky** [comment]
Solved this issue with https://stackoverflow.com/a/55748411/741970 (i.e. https://github.com/josephluck/next-plugin-custom-babel-config)
