### ISSUE TITLE
Doesn't play well with material-ui v4

### ISSUE THREAD

**Issue by williammetcalf** [styled-components/babel-plugin-styled-components#224]
In the newest major update of Material-UI, there is a `styled` function that is *somewhat* similar to `styled-components`. When importing it like:

```ts
import { styled } from "@material-ui/styles"
```

the following error is thrown:

```
[0] const CloseButton = styled(IconButton)({
[0] ^
[0] 
[0] TypeError: styles_1.styled(...).withConfig is not a function
[0] 
[0]   57 | };
[0]   58 | 
[0] > 59 | const CloseButton = styled(IconButton)({
[0]   60 |   position: "absolute",
[0]   61 |   top: 10,
[0]   62 |   right: 10,
[0] 
[0]     at Object../src/common/SomeComponent (/.../SomeComponent.tsx:59:1)
```

However when the imported variable's name is changed, it works. example:

```ts
import { styled as matStyled } from "@material-ui/styles"
```
As best as I can tell this is happening because this babel plugin is seeing the `styled` import and transforming it.

**Comment by probablyup** [comment]
Fun. Any chance you could provide a repro sandbox?

**Comment by lpillonel** [comment]
I am facing the same problem
````...withConfig is not a function````

**Comment by tm1000** [comment]
Ref https://github.com/mui-org/material-ui/issues/16091

**Comment by tm1000** [comment]
Same as @lpillonel I only ran into this when I deleted my package-lock or updated to 1.10.2

**Comment by tm1000** [comment]
The issue is because of the change in #227. Material-ui styled components (which are not styled-components.. ish) look like this:

```
const AdjustButton = styled(IconButton)({
	marginLeft: 'auto',
});
```

In #227 this plugin now looks for `styled(x)({})` where is previously did not. Thus it is catching material-ui...

**Comment by probablyup** [comment]
Tangental issue, the core problem is we aren't checking the import correctly to make sure the import target is one of our whitelisted values in the case of `styled` as a named import. Will fix

**Comment by colemahatmccreary** [comment]
Says its merged, but I'm still getting this error

**Comment by Noob7** [comment]
Im getting the same issue
