### ISSUE TITLE
babel-plugin-styled-components 1.10.1 breaks css prop macro

### ISSUE THREAD

**Issue by jamesknelson** [styled-components/babel-plugin-styled-components#226]
## System:
 - OS: macOS 10.14.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
 - Memory: 346.00 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash

## Binaries:
 - Node: 11.1.0 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm

## npmPackages:
 - styled-components: ^4.3.0 => 4.3.1

## Reproduction

https://github.com/jamesknelson/css-prop-bug-repro/commit/db8250b77c4d950b9bd1b88cece1da96ac8a78df

## Steps to reproduce

Just create a new project with CRA, import `css` from `styled-components/macro`, use it, and the styles don't work.

You can test with this repo:

```bash
git clone git@github.com:jamesknelson/css-prop-bug-repro.git
cd css-prop-bug-repro

# yarn install will not work as there's no yarn lockfile
npm install

# this works.
npm start

# then update babel-plugin-styled-components from 1.10.0 -> 1.10.1
npm install --save babel-plugin-styled-components@1.10.1

# styles disappear.
npm start
```

I've tried this with styled-components 4.2.0, 4.2.1 and 4.3.1. The problem seems to be unrelated to styled-components itself, and is only with `babel-plugin-styled-components`.

## Expected Behavior

Styles for `css` props should work.

## Actual Behavior

Styles for `css` props don't work.

Currently, this breaks all recent versions of styled-components, as unless you specifically install 1.10.0, it will default to 1.10.1.

**Comment by probablyup** [comment]
I'm having trouble figuring out how to actually debug this. Since CRA hides all the babel stuff behind many layers of scripts I can't get access to any console logs etc that I put into the babel plugin itself.

My hunch is that [moving the JSXAttribute visitor up into the Program traversal](https://github.com/styled-components/babel-plugin-styled-components/commit/e3829d28f2b460e097f1499f6091a52b667ef1b4#diff-1fdf421c05c1140f6d71444ea2b27638L13) is what's causing the issue, but I'm not sure _why_ since the macro supposedly runs all the visitors from the babel plugin starting at the root.

**Comment by jamesknelson** [comment]
@probablyup Just tested your theory by manually moving the JSXAttribute visitor into the Program traversal within a working project's `node_modules`, and it caused the same issue.

Conversely, in a 1.10.1 project with SSR using universal-react-scripts, moving the JSXAttribute visitor out of the Program traversal and back up to the top level fixes the css prop, but breaks stable SSR again.

**Comment by probablyup** [comment]
Hoping someone over in the macros repo will have an inkling: https://github.com/kentcdodds/babel-plugin-macros/issues/121

**Comment by jamesknelson** [comment]
My gut feeling is that `Program` isn't being visited, because it's already being visited within babel-plugin macros.

I managed to fix the issue by modifying https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/macro/index.js#L32 to use `@babel/traverse` instead of program.traverse:

```js
traverse(
    program.parent,
    babelPlugin({ types: t }).visitor,
    undefined,
    stateWithOpts,
  )
```

This seems to keep SSR stable, while also working with the macros.

Not sure how to add tests that it works given that it's pretty CRA specific, but if you're okay without tests, shall I submit a PR?

**Comment by probablyup** [comment]
I think there are macro tests in the repo but yeah

**Comment by probablyup** [comment]
Fixed in latest styled-components v4.x!
