### ISSUE TITLE
new version causes compile error

### ISSUE THREAD

**Issue by rafaeldwan** [styled-components/babel-plugin-styled-components#231]
the bump to 1.10.3 caused a compile error on our app - 
```Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: /.../src/components/.../index.jsx: x is not a function
    at .../node_modules/babel-plugin-styled-components/lib/visitors/transpileCssProp.js:117:19```

Rolling back to 1.10.2 fixed the issue.

**Comment by probablyup** [comment]
Hmm. Do you have some babel 6 stuff lingering around in your app? The only thing I can think of that might trigger this is the addition of https://github.com/styled-components/babel-plugin-styled-components/blob/9c4f19f104789299a4d7c4216a1abd0dbfb55bd1/src/visitors/transpileCssProp.js#L132

If an old version of babel types is being used that type function might not exist.

**Comment by probablyup** [comment]
Can you try out 1.10.4? I added a filter to make sure the function exists before checking it.

**Comment by rafaeldwan** [comment]
yes, looks like most of our babel stuff is at ^6.x 
Testing 1.10.4 now

**Comment by rafaeldwan** [comment]
Compiled successfully. Thank you for the prompt fix!

**Comment by probablyup** [comment]
Awesome, glad to hear it!
