### ISSUE TITLE
Next.js app stuck on "compiling" with version >= 1.10.3

### ISSUE THREAD

**Issue by znarf** [styled-components/babel-plugin-styled-components#232]
Our Next.js app is https://github.com/opencollective/opencollective-frontend/

When upgrading to a version >= `1.10.3` of `babel-plugin-styled-components`, our dev environment is unusable, the app is stuck on "compiling ...".

We had to downgrade to version `1.10.2`:
https://github.com/opencollective/opencollective-frontend/pull/2044

**To reproduce:**
- `git clone git@github.com:opencollective/opencollective-frontend.git`
- `cd opencollective-frontend`
- `npm install`
- `npm install babel-plugin-styled-components@1.10.3 --save-exact`
- `npm run dev`
- Go to: `http://localhost:3000/`

**Current behavior**:
- app is stuck on "compiling ..."
- can't load any page.

**Expected behavior**:
- app succeeds compiling
- can load any page

**Comment by probablyup** [comment]
can you try 1.10.4?

**Comment by znarf** [comment]
Same for `1.10.4`.

We actually first encountered this behavior in `1.10.4`, we later tried `1.10.3` with the same result. So, this should have been introduced in `1.10.3`.

**Comment by c0b41** [comment]
same as gatsby, build never completed..
![Ekran Alıntısı](https://user-images.githubusercontent.com/2834954/60388975-37158180-9ac2-11e9-8102-e245bf4a24d5.PNG)

**Comment by nghiepit** [comment]
Same issue
`1.0.2` work fine.

**Comment by Swampy821** [comment]
Adding on this, this broke our build within Docker and took us a long time to pinpoint where it was coming from. You may want to consider reverting back to 1.10.2 to save people that have it marked as `^1.10.0` like we did while you figure out the issue.

**Comment by probablyup** [comment]
Hard to figure out the issue when no one has provided a reproduction.

**Comment by znarf** [comment]
@probablyup I think I gave precise steps to reproduce. Let me know if you need anything else from me.

**Comment by Vanuan** [comment]
Hello from Gatsby users:
https://github.com/gatsbyjs/gatsby/issues/15205

**Comment by Vanuan** [comment]
I think you can use this example: https://github.com/gatsbyjs/gatsby/tree/master/examples/using-styled-components

**Comment by Vanuan** [comment]
People say disabling source maps fixes the issue. Hope it helps

**Comment by znarf** [comment]
For my case, I now tested all commits between `1.1.2` and `1.1.3` one by one. I can now say that this was introduced in https://github.com/styled-components/babel-plugin-styled-components/pull/230

**Comment by ZauberNerd** [comment]
@znarf @probablyup this change causes our builds to get stuck: https://github.com/styled-components/babel-plugin-styled-components/pull/230/files#diff-09a7c7a1456b228d86909e9c7f46ec3f
When I revert just that one line, everything works as it was before.

**Comment by probablyup** [comment]
@ZauberNerd's fix is out in https://github.com/styled-components/babel-plugin-styled-components/releases/tag/v1.10.5

Thanks for debugging and fixing!

**Comment by nghiepit** [comment]
`v1.10.5` not working with me 😢

**Comment by probablyup** [comment]
@nghiepit can you open up a separate issue and provide a reproduction? Thanks

**Comment by znarf** [comment]
`1.10.5` is not fixing the original issue I reported. Please re-open.

**Comment by ZauberNerd** [comment]
Oh, oh, shame on me. I missed the babel cache in `./node_module/.cache/`.. :(
I'm looking into it..

**Comment by znarf** [comment]
@ZauberNerd Thank you for your work on that!

**Comment by probablyup** [comment]
Published a test build under `babel-plugin-styled-components@test` based on @ZauberNerd's next PR. Please report back if it fixes your issue, ty.

**Comment by znarf** [comment]
I tested `1.10.6`and it's fixing the original issue.
