### ISSUE TITLE
Hydrate: "`className` did not match"

### ISSUE THREAD

**Issue by utftufutukgyftryidytftuv** [styled-components/babel-plugin-styled-components#246]
Hello there, as I understand it, I have a standard issue with different classnames on hydrate. What am I doing wrong?
https://github.com/utftufutukgyftryidytftuv/hydrate

**Comment by mxstbr** [comment]
We cannot debug your issues for you, sorry. Common causes for hydration mismatches include relying on `window.innerWidth` and other similarly non-existant properties on the server, maybe that helps!

**Comment by probablyup** [comment]
There's no babel config applying our plugin
