### ISSUE TITLE
Problems with Rollup

### ISSUE THREAD

**Issue by modernserf** [styled-components/babel-plugin-styled-components#247]
I can't seem to get this plugin working with rollup -- at least, not how I'm using rollup.

I have an example project [hosted on Glitch](https://glitch.com/edit/#!/yellow-zenith?path=lib/index.js:12:2), and you can see the results in [a small app](http://yellow-zenith.glitch.me/) and in compiled code, both in [CommonJS](http://yellow-zenith.glitch.me/main.js) and [ES6 module](http://yellow-zenith.glitch.me/module.js) form. The JSX is correctly transpiling, so I know that Babel is at least doing _something_ to my code.

I have also been unable to get this working on importing a rollup-built component library into a [small parcel-based project](http://cliff-bambiraptor.glitch.me/) -- as you can see, the plugin is being applied to _local_ styles, but not the styles from the shared components library.

**Comment by coreybrown89** [comment]
@modernserf did you figure out what your issue was? I'm running into the same problem
