### ISSUE TITLE
How does this plugin give ID-generation consistency?

### ISSUE THREAD

**Issue by sdegutis** [styled-components/babel-plugin-styled-components#254]
If I use this plugin in two different webpack-cli runs, one for the client bundle and one for the server bundle (I know this isn't how webpack is usually used, ignore that for a second), will it still generate consistent IDs? In other words, is its ID generation stateless and a pure function? I assume so because I see that src/utils/hash.js uses MurmurHash2, but I'm just hoping for a quick verification that I'm not missing something. Thanks for your time and for a great plugin.

**Comment by mxstbr** [comment]
Yes, that's the whole point! 👍

**Comment by sdegutis** [comment]
Awesome thanks!
