### ISSUE TITLE
css prop generating different classnames for same component on repitition

### ISSUE THREAD

**Issue by luffyabinash** [styled-components/babel-plugin-styled-components#265]
const greenBgStyle = css`
 background: green;
`;

<p css={greenBgStyle}>Something here</p>
<p css={greenBgStyle}>Something here</p>

The above case generates different class names
Alternatively, if I try the same with

const GreenStyledP = styled.p`background: green`;

<GreenStyledP>Something else here</GreenStyledP>
<GreenStyledP>Something else here</GreenStyledP>

generates same class names for both

Getting the same issue irrespective of production / dev mode

Is this a known behavior ?
( Let me know if you need some reproducible template )

**Comment by kitten** [comment]
Hiya, I know we’ve talked about this on Twitter DMs before but this issue does need more details. The issue template may help: https://raw.githubusercontent.com/styled-components/styled-components/master/.github/ISSUE_TEMPLATE.md

Some proper multi line code blocks would be nice and we need to see an exact description of what you’re seeing vs expecting;

> The above case generates different class names

This is just not precise enough without some context 🙂
