### ISSUE TITLE
Security Patch

### ISSUE THREAD

**Issue by bvandermeersch** [styled-components/babel-plugin-styled-components#285]
Can you patch

Testing /builds/xxx/www/gatsby...
506 Tested 2358 dependencies for known issues, found 1 issue, 6011 vulnerable paths.
507 Patchable issues:
508 Patch available for lodash@4.17.15
509 ✗ Prototype Pollution (new) [Medium Severity][https://snyk.io/vuln/SNYK-JS-LODASH-567746] in lodash@4.17.15
510 introduced by babel-plugin-styled-components@1.10.7 > lodash@4.17.15 and 6010 other path(s)

Security patch avaliable for loadash
https://snyk.io/vuln/SNYK-JS-LODASH-567746

**Comment by probablyup** [comment]
Should be fixed in recent versions
