### ISSUE TITLE
Babel plugin with @xstyled/styled-components

### ISSUE THREAD

**Issue by salper** [styled-components/babel-plugin-styled-components#287]
I'm using a wrapper called @xstyled/styled-components for conveniency. But I can't benefit from the plugin as the top level import paths are static here: https://github.com/styled-components/babel-plugin-styled-components/blob/55b43ee70bdd8cd20ba942577e3747879cf1b44b/src/utils/detectors.js#L1

Would you consider and allow a PR extending this list through plugin options?

**Comment by eugeneross** [comment]
@salper did you manage to get this to work? Using the same wrapper library and have been searching for a solution.

**Comment by salper** [comment]
@eugeneross Sorry for the late answer. You did well.
