### ISSUE TITLE
//-style comments are mangled by the plugin

### ISSUE THREAD

**Issue by wmertens** [styled-components/babel-plugin-styled-components#29]
When using line comments, they get their newline stripped by the minification and they become an erroneous selector.

<strike>I was also not able to turn off minify with the plugin options.</strike> (config error)

I propose that minification be disabled until #26 lands, that will be much more useful and correct.

**Comment by vdanchenkov** [comment]
Why would we do something about it if starting line with `//` is incorrect in CSS?

**Comment by mxstbr** [comment]
> Why would we do something about it if starting line with // is incorrect in CSS?

Because we allow it in `styled-components`. It's something that people did over and over, so we added support for it and basically cut out any line that contains `//`. We should remove those comments with the babel plugin too.

**Comment by vdanchenkov** [comment]
Fixing it will be tricky. I believe it should trim the code after the `//` unless `//` is inside quotes. And preserve code to the left of `//`. I think that the easiest fix would be to keep newline at the end of the line if it contains '//' and hope stylis will do the rest.

I hadn't looked into #26 yet. Hope it will give good enough size of the output, so we can replace minification with it once it's completed.

**Comment by wmertens** [comment]
Stylis just supports it, so do you really need to strip those out?

**Comment by kopax** [comment]
any update on this ?
