### ISSUE TITLE
v1.11.0 a few times slower

### ISSUE THREAD

**Issue by khmm12** [styled-components/babel-plugin-styled-components#293]
After upgrade to v1.11.0 from v1.10.7 I noticed that builds became much longer.

## Tools:

```
node: 12.16.0
webpack: 4.44.1
```

## Plugin configuration

```js
  ssr: true,
  pure: true,
  displayName: false,
  fileName: false
```

## Test conditions

- Same machine and OS.
- Same dependencies except babel-plugin-styled-components version.
- No cache on every build.
- Result is calculated as average on 4 builds.

## Results:
|1.10.7|1.11.0|
|-|-|
|46.4325s|136.11s|

## Shallow investigation

Try to revert https://github.com/styled-components/babel-plugin-styled-components/pull/283. Results became betters, similar to 1.10.7 🎉.

Let's go deeper. 

https://github.com/styled-components/babel-plugin-styled-components/blob/ccc15c5c0d4bce5a8481d49b35307a1a911342c5/src/utils/detectors.js#L17
https://github.com/styled-components/babel-plugin-styled-components/blob/ccc15c5c0d4bce5a8481d49b35307a1a911342c5/src/utils/detectors.js#L21
https://github.com/styled-components/babel-plugin-styled-components/blob/ccc15c5c0d4bce5a8481d49b35307a1a911342c5/src/utils/detectors.js#L25
https://github.com/styled-components/babel-plugin-styled-components/blob/ccc15c5c0d4bce5a8481d49b35307a1a911342c5/src/utils/detectors.js#L10

A module doesn't contain styled-components imports? No worries, on next expression we will definitely find them! 

Of course I saw the support of `css-prop`, where the visitor may modify imports. But it in mixed case depending on expressions order it may skip `styled.` declarations.

<details>
<summary>`styled`, then `css` prop</summary>

<details>
<summary>input</summary>

```jsx
import React from 'react'

const Title = styled.h1`
  font-size: 10px;
`

const TestComponent = () => (
  <div css={`width: 10px;`}>
    <Title>Title</Title>
  </div>
)
```
</details>

<details>
<summary>output</summary>

```js
import _styled from "styled-components";
import React from 'react';
const Title = styled.h1`
  font-size: 10px;
`;

var _StyledDiv = /*#__PURE__*/_styled("div").withConfig({
  componentId: "dh69fc-0"
})(["width:10px;"]);

const TestComponent = () => /*#__PURE__*/React.createElement(_StyledDiv, null, /*#__PURE__*/React.createElement(Title, null, "Title"));
```
</details>
</details>

<details>
<summary>`css` prop, then `styled</summary>

<details>
<summary>input</summary>

```jsx
import React from 'react'

const TestComponent = () => (
  <div css={`width: 10px;`}>
    <Title>Title</Title>
  </div>
)


const Title = styled.h1`
  font-size: 10px;
`
```
</details>

<details>
<summary>output</summary>

```js
import _styled from "styled-components";
import React from 'react';

var _StyledDiv = /*#__PURE__*/_styled("div").withConfig({
  componentId: "dh69fc-0"
})(["width:10px;"]);

const TestComponent = () => /*#__PURE__*/React.createElement(_StyledDiv, null, /*#__PURE__*/React.createElement(Title, null, "Title"));

const Title = styled.h1`
  font-size: 10px;
`;
```
</details>
</details>

**Comment by probablyup** [comment]
_sigh_ was hoping that wouldn't be the case. Can you send a revert PR?

**Comment by khmm12** [comment]
@probablyup Sure, just a second

**Comment by khmm12** [comment]
@probablyup v1.11.1 became faster as before 🎉. Thank you!
