### ISSUE TITLE
Fix identifiers

### ISSUE THREAD

**Issue by mxstbr** [styled-components/babel-plugin-styled-components#3]
I forgot that the identifiers actually don't need to be added to the underlying component but to the actual component:

```JS
const Test = styled.div``;
Test.identifier = 1;
```

What I do right now (which is wrong) is this:

```JS
const Test = function() {
  const c = styled.div``;
  c.identifier = 1;
}();
```

Switching to the first one will be a bit harder, and since we're still exploring possible other syntaxes I'm going to invest a large amount of time into fixing this, since we probably won't keep it around anyway. /cc @geelen

**Comment by geelen** [comment]
I don't quite understand the difference...

**Comment by mxstbr** [comment]
The second one has more code, but I guess it doesn't really matter. Closing for now.
