### ISSUE TITLE
Uncaught TypeError: styled.css.withConfig is not a function

### ISSUE THREAD

**Issue by Dstklr** [styled-components/babel-plugin-styled-components#303]
Hi,
When using react SSR + styled components and adding the current plugin "babel-plugin-styled-components" I get the following error:
Uncaught TypeError: styled.css.withConfig is not a function
    at Object.<anonymous> (index.cjs.js:1)
    at Object.<anonymous> (bundle.js:38885)
    at __webpack_require__ (bootstrap:19)
    at Object.<anonymous> (Table.jsx:4)
    at __webpack_require__ (bootstrap:19)
    at Object.<anonymous> (index.js:20)
    at __webpack_require__ (bootstrap:19)
    at Object.<anonymous> (layout.jsx:3)
    at __webpack_require__ (bootstrap:19)
    at Object.<anonymous> (routes.jsx:3)

my **babel.config.js** is configured in the following way:

module.exports = function init(api) {
  const outputPath = '/dist/public';
  // determine where the resources (images, bundle, and outer js) should be served from.
  // we set the path to point to resource ms.
  const publicPath = '/';
  api.cache.never();
  const presets = ['airbnb',
    '@babel/preset-env',
    '@babel/preset-react'];
  const plugins = [
    'babel-plugin-styled-components',
    [
      'file-loader',
      {
        name: '[name].[hash].[ext]',
        extensions: ['png', 'jpg', 'jpeg', 'gif'],
        outputPath,
        publicPath,
        context: '',
        limit: 0,
      },
    ],
];

  return {
    presets,
    plugins,
  };
};

**NOTE:** if not using the "babel-plugin-styled-components" plugin - the app works fine.

please assist on the matter.
thanks.

**Comment by randalmaia** [comment]
I have the same issue

**Comment by probablyup** [comment]
Going to close as this issue doesn't include a reproduction case, so it's not possible to debug. Feel free to open a new issue with a reproduction using a tool like codesandbox
