### ISSUE TITLE
SC classes are made equal between *different* components

### ISSUE THREAD

**Issue by thany** [styled-components/babel-plugin-styled-components#305]
Take these components:

```js
const createTableCell = (width) => styled.td`
  width: ${width};
`;

const TableCells = {
  Project: createTableCell('40%'),
  Inquired: createTableCell('18%'),
  CaseNumber: createTableCell('18%'),
  Status: createTableCell('24%'),
};
```

This is greatly simplified, but it does illustrate the pattern I'm using. Without BPSC, the classes for these components are different from each other, which is correct. With BPSC, *even* with `displayName` and `fileName` set to `false`, these components get the same classname, namely that of the first table cell, because they all get 40% width.

Here's how they're used:

```jsx
<TableCells.Project>
  Foobar
</TableCells.Project>
<!-- etc -->
```

Fairly straight-forward.

And the resulting HTML *without* BPSC:

```html
<td class="sc-pTTZH WUjKp">...</td>
<td class="sc-qcpaC jiveQf">...</td>
<td class="sc-oVrHh guPJns">...</td>
<td class="sc-pdMIc htNftY">...</td>
```

And *with* BPSC:

```html
<td class="sc-1mriuqq-2 kmMDBu">...</td>
<td class="sc-1mriuqq-2 kmMDBu">...</td>
<td class="sc-1mriuqq-2 kmMDBu">...</td>
<td class="sc-1mriuqq-2 kmMDBu">...</td>
```

Versions:
React 16.13.1
Styled-components 5.1.1
Babel 7.8.6
BPSC 1.11.1

**Comment by mxstbr** [comment]
That is correct. We create a classname per `styled.x` call. Try doing this instead:

```JS
const TableCell = styled.td`
  width: ${props => props.width};
`;

const TableCells = {
  Project: (props) => <TableCell width="40%" {...props} />,
  Inquired: (props) => <TableCell width="18%" {...props} />,
  CaseNumber: (props) => <TableCell width="18%" {...props} />,
  Status: (props) => <TableCell width="24%" {...props} />,
};
```

**Comment by thany** [comment]
> That is correct. 

I really don't think it's quite correct. It's *overwriting* the SC classnames. Shouldn't it only *append* one?
