### ISSUE TITLE
namespace option prefixes sc-xxx class instead of the other one with styled

### ISSUE THREAD

**Issue by mattleonowicz** [styled-components/babel-plugin-styled-components#308]
I think `namespace` option should prefix the other class, that actually contains css rules (or both of them).

See https://github.com/styled-components/styled-components/pull/3225, https://github.com/styled-components/styled-components/issues/3186

**Comment by mxstbr** [comment]
Agreed, I think it should prefix both classes. This needs to be implemented in the core repo.

**Comment by ignj** [comment]
@mxstbr do you know if this feature is being tracked somewhere?

**Comment by rafael-cineis-ifood** [comment]
@mxstbr @probablyup any updates on this? Is it not possible to prefix everything using the babel-plugin? I mean, to prefix the other classes generated based on the props (the ones that hold the CSS itself)
