### ISSUE TITLE
Add non-hashed className

### ISSUE THREAD

**Issue by Munter** [styled-components/babel-plugin-styled-components#309]
Currently, this plugin helps me take a human non-readable className and prepend some extra stuff that helps it become more humane readable. That's great. There's another use case that I really need to be covered through:

Consistent className across changes.

Like many others, I am running a site where we want to track user events. These event tracking handlers are not set up by developers with access to the source code, but rather by marketers that have to use the build output as an API. This is where styled-components currently have a massive downside. Any change to a component invalidates the className. Not just the small hash that's actually used as a selector, but also the human friend className. Any change to the component invalidates the interface marketers are counting on.

It gets even worse. Many marketers don't write their CSS selectors by hand, but rather use a visual tool that lets them click an element on a page and the tool auto generates a CSS selector. This sort of automation is very difficult to get right, and it turns out many tools don't really put much effort into trying that at all. Here are a few example selectors from the [Segment](https://segment.com/) visual tagger tool:

```css
div > .coreActionButton__Wrapper-sc-1gx4txn-0 > .coreActionButton__StyledActionButton-sc-1gx4txn-1 {}

.websiteLayout__Row-sc-15nycle-9 > .websiteTestimonials__TestimonialBox-sc-1l6bnrc-6:nth-child(2) > .coreButtonLink__LinkButton-sc-1yjypjz-0 {}

div > .websiteLayout__Stack-sc-15nycle-8 > form {}
```

As you can see there is one thing wrong with these selectors, which falls within the scope of this plugin to be able to fix:

**The only className they have available contains a hash of the styling. If the styling changes, the selector matches nothing**

Now, there are multiple other things wrong with these auto-generated selectors, like depending on exact nesting and `nth-child`-offset, but those are faults of the visual tagging tool.

## Proposal

Add the human-readable part of the current className that consists of `[human-readable]-[hash]` ad an addition to the current one: `[human-readable] [human-readable]-[hash] [cs-internal-hash]`.

This would create a more stable external API that both humanly written selectors and robot generated selectors could use.

Examples of the above selectors with the proposal applied:

```css
div > .coreActionButton__Wrapper > .coreActionButton__StyledActionButton {}

.websiteLayout__Row > .websiteTestimonials__TestimonialBox:nth-child(2) > .coreButtonLink__LinkButton {}

div > .websiteLayout__Stack > form {}
```

I think such an output would create a more stable tracking ability.

**Note:** I think most of these auto generator tools prefer `id` over `class` if available. But when they do select on `class` they seem to prefer the first one

**Comment by gajus** [comment]
I just tried replicating this issue and couldn't understand what is the problem.

```js
<div
  css={css`
    color: #f00;
  `}
>
  Hello, World!
</div>

```

generates:

```html
<div class="foo___StyledDiv-ejl2d6-0 hkkBWO">Hello, World!</div>

```

and

```js
<div
  css={css`
    color: #f00;
    background: #00f;
  `}
>
  Hello, World!
</div>

```

generates:

```html
<div class="foo___StyledDiv-ejl2d6-0 fEyIfo">Hello, World!</div>

```

i.e. The root class name does not change.

**Comment by gajus** [comment]
For what it is worth, this is my `.babelrc.js` configuration:

```js
module.exports = {
  presets: [
    'next/babel',
  ],
  plugins: [
    [
      'styled-components',
      {
        displayName: true,
        ssr: true,
        preprocess: false,
      }
    ],
  ]
};

```

**Comment by gajus** [comment]
I think you might be missing the [`ssr`](https://styled-components.com/docs/tooling#serverside-rendering) configuration.

I can confirm that indeed without `ssr` you will get unique hash every time.
