### ISSUE TITLE
Is styled-components peer dependency actually required?

### ISSUE THREAD

**Issue by otakustay** [styled-components/babel-plugin-styled-components#319]
`babel-plugin-styled-components` has a peer dependency of `"styled-components": ">= 2"`, however it seems to work perfectly without `styled-components` installed.

This can be a confusing issue when we provides a team-wide universal babel config, our developers may or may not use `styled-components` in their apps, but we're trying to satisfy all situation so we have to include this plugin.

**Comment by probablyup** [comment]
Peer dependencies are just a hint on what version of the library works with the plugin

**Comment by otakustay** [comment]
If this is the only purpose, can we add a [peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) to mark it as optional? If acceptable I'm going to create a pull request for it
