### ISSUE TITLE
Cannot pass plugin options? 

### ISSUE THREAD

**Issue by davidrossjones** [styled-components/babel-plugin-styled-components#32]
NPM install of `babel-plugin-styled-components` with following `.babelrc`:

~~~
{
  "plugins": ["styled-components", {
      "displayName": false
    }]
}
~~~

When run with babel-cli (or via webpack) I get the following:

~~~
Error: Plugin 1 specified in ".babelrc" provided an invalid property of "displayName"
~~~

This is the same for all options (ssr, minify, displayName). When passing no options, the plugin appears to be working as expected with friendly component names showing via inspector/dev tools. What am I doing wrong?

**Comment by wmertens** [comment]
It works for me with `[require.resolve('babel-plugin-styled-components'), {minify: false}],`; I think you need to specify the full module name, otherwise it finds `styled-components`.

**Comment by philpl** [comment]
@davidrossjones You forgot to wrap the plugin inside an array ;)

```
{
  "plugins": [
    ["styled-components", {
      "displayName": false
    }]
  ]
}
```

**Comment by philpl** [comment]
![download-2](https://cloud.githubusercontent.com/assets/2041385/23922435/3e6fdb1c-08fa-11e7-98fd-2a1a3228dc07.gif)

**Comment by mxstbr** [comment]
Sorry, thanks @philpl!

**Comment by philpl** [comment]
@mxstbr haha no apologies or anything needed. I just felt like posting a gif 😅
