### ISSUE TITLE
Is there a simple way to suffix every css property with `!important` ?

### ISSUE THREAD

**Issue by vinzcelavi** [styled-components/babel-plugin-styled-components#324]
Hello there,

It's not really an issue, but I'm wondering if this would be helpful for someone else than me and if it is meaningful to add it in option. I'm developing a react components library and it would be nice to have this option.

Tailwind has it option https://tailwindcss.com/docs/configuration#important

Maybe this is not the philosophy of styled-components but I had to ask.
Thanks !

**Comment by probablyup** [comment]
> Hello there,
> 
> It's not really an issue, but I'm wondering if this would be helpful for someone else than me and if it is meaningful to add it in option. I'm developing a react components library and it would be nice to have this option.
> 
> Tailwind has it option https://tailwindcss.com/docs/configuration#important
> 
> Maybe this is not the philosophy of styled-components but I had to ask.
> Thanks !

Hey there, this sort of thing is a perfect use case for a stylis plugin. Since v5 you can provide your own plugins :)

**Comment by vinzcelavi** [comment]
Ok thank you @probablyup I'll check this out !
