### ISSUE TITLE
plugin's configuration doesn't work with custom .babelrc in NextJs

### ISSUE THREAD

**Issue by AngryBotIY** [styled-components/babel-plugin-styled-components#330]
I have installed in my project: `"babel-plugin-styled-components": "^1.12.0"`

Followed by documentation I created custom .babelrc file:
`"plugins": [
    [
      "styled-components",
      { "ssr": false, "displayName": true, "preprocess": true }
    ]`

results:

- There is no display name
![image](https://user-images.githubusercontent.com/51003204/121191988-299fcf00-c875-11eb-8351-80c461f8f983.png)

- ssr option just ignored (collected style sheet included in server response)
![image](https://user-images.githubusercontent.com/51003204/121192352-87ccb200-c875-11eb-8b15-c485687736fb.png)

- endless warning about mismatching classnames
![image](https://user-images.githubusercontent.com/51003204/121192453-a468ea00-c875-11eb-9a2e-2e398e85cabf.png)

How to resolve all of this issues?

versions:
```
"next": "^10.2.0"
"styled-components": "^5.3.0"
```

**Comment by sumitduggal** [comment]
are you trying to Server side render this app? If so the **classnames** generated on server side does not match with clientside after hydration, hence you see this error.
try changing you babel config to `"plugins": [ [ "styled-components", { "ssr": true, "displayName": true } ]`

**Comment by probablyup** [comment]
I think you'd still need to add `next/babel` to presets for a custom babel config?

**Comment by AngryBotIY** [comment]
I just migrated to "emotion" because "styled" plugin doesn't work as expected
