### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by miladMAPS** [styled-components/babel-plugin-styled-components#337]
When i try to use this syntac `css={{ ...css, ...(playing ? { opacity: 0, bottom: "-100px" } : {}) }}`, it fails and it says `TypeError: Cannot read property 'reduce' of undefined`
here is my code:

![Screen Shot 2021-07-03 at 9 13 13 PM](https://user-images.githubusercontent.com/57092046/124361304-a55a2500-dc43-11eb-8ab4-b1388a4720ae.png)

![Screen Shot 2021-07-03 at 9 17 57 PM](https://user-images.githubusercontent.com/57092046/124361379-29aca800-dc44-11eb-99cc-4a525ef20796.png)

![Screen Shot 2021-07-03 at 9 18 34 PM](https://user-images.githubusercontent.com/57092046/124361392-49dc6700-dc44-11eb-9f9c-2a72382ca96f.png)

![Screen Shot 2021-07-03 at 9 18 44 PM](https://user-images.githubusercontent.com/57092046/124361402-4fd24800-dc44-11eb-83d7-73b731f1d139.png)

sorry i don't have time to prepare a workaround 
if it's not possible for you to debug in this way i can do something about that.

**Comment by probablyup** [comment]
Thanks for the code sample, will work on a patch!

**Comment by probablyup** [comment]
@miladMAPS could you please try out `1.13.2-test.0` and let me know if it fixes your issue?
