### ISSUE TITLE
[v1.0.1] Possible bug: debug displayname (and styled-components v2).

### ISSUE THREAD

**Issue by HejdesGit** [styled-components/babel-plugin-styled-components#35]
Hello,

I just upgraded (babel-plugin-styled-components) from v:1.0.0 to v:1.0.1 and now the plugin dons't add the components' name to the class name.

Div with v:1.0.1: `<div data-reactroot="" class="c4dx7z-0 bUnYA">`
Div with v:1.0.0: `<div data-reactroot="" class="app__DivFlexWrapper-14dsmrv jSMEYv">`

Using: 
"styled-components": "~2.0.0-8"

Babelrc: 
.babelrc
{
    "presets": [
        "es2015",
        "react"
    ],
    "plugins": [
        "transform-object-rest-spread",
        "transform-class-properties",
        "styled-components",
        "react-hot-loader/babel"
    ]
}

I know that this plugin might not be compatible with styled components 2, but would like to let you know and see if I'm doing something wrong.

**Comment by kopax** [comment]
@HejdesGit this plugin is meant to work with `styled-components` 2. I haven't  tried the 1.0.1 and I think I will wait a bit.

**Comment by mxstbr** [comment]
The plugin is actually _only_ compatible with v2. Do you have a reproduction repo of this somewhere? It should definitely not be happening.

**Comment by HejdesGit** [comment]
@mxstbr sorry, no reproduction repo. Didn't have time to set one up. But the latest release (1.1.1) is fixing my problem. Hope that's good enough. If the problem arise again I'll try to investigate further and set up a repo.

**Comment by vdanchenkov** [comment]
Component name was dropped from the id starting from 1.0.1. Yes, it had to be mentioned explicitly. Starting from 1.1.0 ssr flag is disabled by default, so id is not generated at all, which "fixes" the problem because id is now generated by the runtime, not the plugin. see #44
