### ISSUE TITLE
Error "withConfig is not a function"

### ISSUE THREAD

**Issue by acanimal** [styled-components/babel-plugin-styled-components#36]
Hi,
I just installed the plugin as described but when I try to bundle code using webpack the next error arise:

`TypeError: _styledComponents2.default.h1.withConfig is not a function`

Am I missing something? Any help?

**Comment by philpl** [comment]
Are you trying to use it with styled-components v1 possibly?

**Comment by scottluptowski** [comment]
I am receiving the same error and am using Styled Components v1.

Will try now with v2. Thanks!

**Comment by mxstbr** [comment]
This plugin only works with v2—we should add that to the README!
