### ISSUE TITLE
displayName not working with styled-components/macro

### ISSUE THREAD

**Issue by joshwcomeau** [styled-components/babel-plugin-styled-components#371]
Hi there!

`styled-components/macro` allows the developer to enjoy the benefits of the `displayName` property without needing to tinker with a babel config / eject a create-react-app application.

Here's a CodeSandbox showing the issue: 
https://codesandbox.io/s/cold-flower-5orvj

**Expected behavior:** The `<Thing>` component should render as a div with `class="App__Thing-sc-123abc"`
**Actual behavior:** The `<Thing>` component is rendering as a div with `class="sc-abc123"`.

I checked, and this appears to have broken with [the 2.0.0 release](https://github.com/styled-components/babel-plugin-styled-components/releases/tag/v2.0.0); it worked immediately previous, in 1.13.3.

Let me know if I can do anything else to help!

**Comment by rockwotj** [comment]
This seems to be fixed in the latest release

**Comment by agriffis** [comment]
@joshwcomeau Fixed in v2.0.6?

**Comment by Morpa** [comment]
I tried v2.0.7,  and I got the same error

**Comment by OmarKhled** [comment]
it's working now in v2.0.7!
