### ISSUE TITLE
bumping the babel-plugin-styled-components to 2.0.5 make a regression in performance inside our tests

### ISSUE THREAD

**Issue by daniloab** [styled-components/babel-plugin-styled-components#373]
Bumping the babel-plugin-styled-components to the last version 2.0.5 makes the performance from our tests decrease a lot making a unique test take at least 8 minutes to run and breaking it.

By now, our fix was reverted to the previous version 2.0.4 and our tests start to run normally again.

before bump
![Screen Shot 2022-02-24 at 14 33 59](https://user-images.githubusercontent.com/19939822/155577397-8283e8da-fbf2-4628-8ac4-353ea5104f26.png)

after bump
![Screen Shot 2022-02-24 at 14 33 37](https://user-images.githubusercontent.com/19939822/155577420-54ed352a-a4dd-4902-a3ba-9cfceec5781d.png)

reverting bump
![Screen Shot 2022-02-24 at 14 37 54](https://user-images.githubusercontent.com/19939822/155577655-75215a2c-9c02-4a6e-98af-b5f64630dd28.png)

**Comment by janicduplessis** [comment]
I'm also seeing a major perf regression of my website build after bumping to 2.0.5, 2.0.4 is fine. At runtime I also get a `_styled is not defined` error. From inspecting the code it seems like the styled component import is not added automatically.

**Comment by helciofrancotc** [comment]
I have the same problem here, but with the NextJS build.
It took 3 minutes and now it takes over 20 minutes.

**Comment by jordan-brough** [comment]
We're seeing build times increase so much that automated builds are timing out if we try to update from 2.0.3 to 2.0.5.

**Comment by probablyup** [comment]
Thank you, I'm going to revert the last change. Is 2.0.4 as bad or just 2.0.5?

**Comment by jordan-brough** [comment]
Thanks. v2.0.6 seems to have fixed the issues we were seeing. 👍
