### ISSUE TITLE
Babel and corresponding core packages versions 6.25.0 and prior have already reached their end of life.

### ISSUE THREAD

**Issue by JoerKul** [styled-components/babel-plugin-styled-components#388]
I would like to point out that the npm package babel has announced an end of life (EOL) with the Babel ≤ 6.25.0 and has switched to a mono repository. Is planned to change the package babel-plugin-syntax-jsx@6.18.0 in babel-plugin-styled-component to the current mono repository version [babel-plugin-syntax-jsx](https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-jsx) of babel? 

[Babel EOL Announcement](https://github.com/babel/babel/blob/master/SECURITY.md)

**Comment by probablyup** [comment]
Yeah

**Comment by quantizor** [comment]
All set https://github.com/styled-components/babel-plugin-styled-components/releases/tag/v2.1.4
