### ISSUE TITLE
Information about new warning in documentation

### ISSUE THREAD

**Issue by kopax** [styled-components/babel-plugin-styled-components#39]
> :warning: This plugin is only necessary if you're server-side rendering, you can use styled-components perfectly fine without it! :warning:

I was using plugin v1.0.0 to compress my distribution build. Is this included by default in styled-components@? without any plugin ?

**Comment by mxstbr** [comment]
Nope, the warning says "is only _necessary_", not "should only be used when"! Any ideas how to improve that phrasing to make it clearer?

**Comment by kopax** [comment]
Well, the warning is false in this case.

> :warning: This plugin is required if you're using server-side rendering and necessary if you require production distribution optimization, you can use styled-components perfectly fine without it! :warning:

**Comment by mxstbr** [comment]
> it is also necessary for optimizing the production build

Not true, it's not _necessary_ in that case, that's exactly what I was trying to avoid saying! :wink: There's lots of people using `styled-components` in production without this plugin, and if we start saying that people will think they can't use `styled-components` with `create-react-app`.

I agree that we need to change the wording though, what about:

> ⚠️ This plugin is recommended to use with `styled-components` to get a smaller production bundle, but it's **only necessary if you're server-side rendering**. You can use styled-components perfectly fine without it! ⚠️
