### ISSUE TITLE
Uncaught TypeError: _styledComponents2.default.div.withConfig is not a function

### ISSUE THREAD

**Issue by cjthedizzy** [styled-components/babel-plugin-styled-components#43]
I added the plugin without any additional config to my babelrc:

```
{
    "presets": [
        "es2015",
        "react",
        "stage-2"
    ],
    "plugins": [
        "transform-class-properties",
        "styled-components",
        [
            "module-resolver",
            {
                "root": [
                    "./src/javascript"
                ],
                "alias": {
                    "actions": "actions",
                    "components": "components",
                    "constants": "constants",
                    "config": "config",
                    "libs": "libs",
                    "store": "store",
                    "styles": "styles",
                    "utils": "utils",
                    "middleware": "middleware"
                }
            }
        ]
    ]
}
```

Everything worked perfectly before adding the plugin and now I'm getting this error:
`Uncaught TypeError: _styledComponents2.default.div.withConfig is not a function`

The code its throwing on is:
```
const App = styled.div`
        min-height: 100%;
        background-position: center center;
        font-size: 1em;

        ${media.mobile`
            font-size: 1.05em;
        `}
        ${media.largeMobile`
            font-size: 1.2em;
        `}
        ${media.tablet`
            font-size: 1.3em;
        `}
        ${media.desktop`
            font-size: 1.4em;
        `}
        ${media.largeDesktop`
            font-size: 1.25em;
        `}
`;
```

**Comment by cjthedizzy** [comment]
_Side note: I only want to use this for better debug info/more semantic classnames. Im not attempting to use it for SSR_

**Comment by cjthedizzy** [comment]
I just noticed a PR to add that this only works with v2. Seems like that might be my issue since im using 1.1.4. Is v2 stable?

**Comment by philpl** [comment]
@cjthedizzy v2 is scheduled for release soon, and sufficiently stable in terms of tests. We did have a regression lately which mangled styoe ordering, but we fixed it as soon as it came up.

So all in all, it depends on your project. I'd say it's sufficiently stable for most projects

**Comment by cjthedizzy** [comment]
Awesome, the project wont go out for some time so if anything arises, Ill file another issue. Thanks for the quick response!
