### ISSUE TITLE
Option for ssr clashes with displayName

### ISSUE THREAD

**Issue by 0x80** [styled-components/babel-plugin-styled-components#44]
If you set `ssr: true` the component names are not part of the classes anymore. Even if you add `displayName: true`.

If this is intentional it should be mentioned I guess.

**Comment by philpl** [comment]
It should indeed be used. See here: https://github.com/styled-components/styled-components/blob/v2/src/models/ComponentStyle.js#L24

Can you post an example?

**Comment by 0x80** [comment]
I don't have an example ready yet. But the difference in my babel config is this

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      }
    }],
    "flow",
    "react",
    "stage-1"
  ],
  "plugins": ["add-module-exports", "flow-react-proptypes", ["styled-components", {
    "ssr": false
  }]]
}
```


And with changing false -> true,  the difference in output is

```html
<section class="Navbar__Main-iztCjN gzNxuX"></section>
```

vs

```html
<section class="ib60sg-0 fMQjyZ"></section>
```

**Comment by ehd** [comment]
Hey, I’m seeing the same behavior. With 1.1.4 and the default config I see the `displayName` as part of the class, with `ssr: true` it’s gone. Currently getting around this with two different babel envs.

**Comment by vdanchenkov** [comment]
@ehd May I ask, why would you need a component name in the class with ssr enabled? Is it to help with navigation or leads to incorrect behavior?

**Comment by vdanchenkov** [comment]
This difference in the presentation should be addressed in the runtime code, but we can discuss it here, I think.

**Comment by griffinmichl** [comment]
+1 on this issue.

We want component names with SSR enabled @reddit both for debugging (we develop with SSR enabled since SEO is a major part of our business) and to allow users to hook into our styles and provide their own customization to subreddits.

Any updates?

**Comment by mxstbr** [comment]
> If no one's working on this I can look into it.

That'd be awesome! I think this would need a PR against styled-components main, since I think the babel plugin passes down the "nice component name" either way?

**Comment by griffinmichl** [comment]
@mxstbr It looks like it does pass down the displayName, so I'll investigate why they're not showing up in styled-components main

**Comment by philpl** [comment]
So, to bring some clarity here. I misunderstood this issue before. When `ssr` is true, `componentId ` is set to a generated, unique hash. Thus the className is not readable anymore, when it's set.

When it's not set, the `displayName` is used to generate a `componentId`, which then ends up being readable.

We should make a small change that appends `displayName` to the `componentId`, when both options are set :smile:

**Comment by vdanchenkov** [comment]
Appending in a plugin would slightly increase bundle size due to, well, duplication. Why do it here if is can be done in runtime?

**Comment by philpl** [comment]
@vdanchenkov true! let's move this effort to the runtime :)

**Comment by evan-scott-zocdoc** [comment]
@philpl I'm running into this too - the option to enable `displayName` with `ssr` on would be greatly appreciated.

**Comment by philpl** [comment]
@evan-scott-zocdoc this was actually resolved a longer while ago and released with v2 https://github.com/styled-components/styled-components/pull/821

**Comment by evan-scott-zocdoc** [comment]
Oh weird... okay I'll look again.

**Comment by TomLingham** [comment]
Hmm... I'm getting this once again with styled-components 3.3.3, when setting both ssr to true, and displayName to false. Hydrating on the client causes a `Prop `className` did not match. Server` error.

**Comment by probablyup** [comment]
Can you double check it is being deduped correctly by npm?

**Comment by TacoMantra** [comment]
I am not seeing component or filenames in displayName when using renderToNodeStream. I have set displayName to true.  Is this a known issue? Using styled-components 4.0.3 and version 1.8.0 of this plugin.

**Comment by kitten** [comment]
@TacoMantra are you somehow transpiling / bundling your server code so the plugin is applied there as well? If not then your code will be missing the Babel plugin's configs.

Also it's most of the time a better idea to open a new issue than to reply to a year old thread :) this way it'll be easier for you to ask questions and to explain your project's setup

**Comment by TacoMantra** [comment]
@kitten we were not transpiling the server code, but doing so did not resolve the issue. I'll open a new issue, thanks.
