### ISSUE TITLE
Using 2.0.0-17 of styled-components doesn't correctly extract styles for extended classes serverside

### ISSUE THREAD

**Issue by romellogood** [styled-components/babel-plugin-styled-components#47]
With the following code

```
const Paragraph = styled.p`
  font-size: 24px
`;

const Title = styled(Paragraph)`
  color: 'red';
`;

const Example = props => {
  const {text} = props;

  return (
    <Title>{Hello World}</Title>
  );
};
```

The color and font-size rules are split into two different classes but only the color class is sent from the server. When the page renders styled-components correctly renders both styles.

Here is the config babel is using

```
["styled-components", {
      "minify": true,
      "ssr": true
    }]
```

**Comment by philpl** [comment]
Styles aren't extracted by this plugin at all. This is a work in progress. :wink:

**Comment by mxstbr** [comment]
> The color and font-size rules are split into two different classes but only the color class is sent from the server. When the page renders styled-components correctly renders both styles.

That's still a bug I'm pretty sure?

**Comment by philpl** [comment]
@mxstbr Could be? 🤔 

@romellogood Can you post your code before and after transpilation?

**Comment by romellogood** [comment]
```
<p class="fwwwt4-0 XtIyK s1tqgosa-0 hFCZie" data-reactid="5">WELCOME TO THE HOME PAGE</p>

.XtIyK {
    color: #0DA548;
}

.fwwwt4-0 {
}

.hFCZie {
    font-size: 24px;
}

.s1tqgosa-0 {
}

.XtIyK {
    color: #0DA548;
}
```

Here is the transpired code for the snippet above. This is after the client takes over and correctly adds the font-size 24px. 

I beginning to think the issue may be with ServerStyleSheet generating the css on the server instead of the plugin.

**Comment by philpl** [comment]
Can you post the transpiled JS code of your example above, after it's gone through babel, so we can see if it's a problem with styled-components or our babel plugin? :smile:

Cheers :wink:

**Comment by romellogood** [comment]
Closing. I am no longer seeing this issue in 2.2.0
