### ISSUE TITLE
Different class names when rendering on client vs server

### ISSUE THREAD

**Issue by sphinxominator** [styled-components/babel-plugin-styled-components#51]
I'm trying to add SSR to a project based on Create React App. On my backend I got it to render the correct CSS by using this babel plugin and adding `ssr: true` to my `.babelrc` file, but now the class names are not the same as when they're client rendered.

I'm using the newest version `2.0.0` on both the client and server, but since I haven't ejected CRA, I can't add a babel loader to it and I'd prefer not to eject.

The client class names has a `sc-` prefix and looks like `sc-bdVaJa jfEfSr`, while the server rendered ones do not and also have different hashes.

Is this possible to fix? And should it be? I'm thinking now that having two different ways of transpiling my code on the client and server will lead to trouble in other places eventually. But I'm also curious as to why the hashes are different, I'm guessing this plugin handles it differently than the main `styled-components` does?

**Comment by philpl** [comment]
You need to apply the same transformation to client and server files, assuming the files are not universal :) otherwise the client is not going to have the same data attached to it to render with the same className
