### ISSUE TITLE
Clarifications of "improved debugging" and component names.

### ISSUE THREAD

**Issue by elstob** [styled-components/babel-plugin-styled-components#53]
Hi, I implemented this plugin on the client side of our application. (This may have been my first mistake). Because I was hoping to get the Devtools names functionality i.e `ComponentName` instead of `styled.div` in my DomTree, as well as classNames like sc-ComponentName.

Unfortunately none of these things seem to be happening. I still have `styled.div` lying around and classes are in the vein of `sc-jfkdl poijl`. Not what I was expecting. Could you clarify that if I'm doing something like:

```javascript
const MyComponent = styled.div`
  color: red;
`;
```

I should be seeing either `<MyComponent ...>` in my React Devtool and `<div className="sc-MyComponent">` in my element inspector? Or is this functionality for server side generation early? If I should be expecting to see that any ideas what I might be doing wrong? I know the Readme states the plug in is for serverside usage only but it's not 100% clear if that's solely for server side rendering or all the additional functionality underneath that section.

Thanks!

**Comment by nickbalestra** [comment]
We had it working as @elstob expected during the Styled-components 2.0 RC phase, but somehow `displayName` doesn't produce the same visible result anymore

Currently running on 
- "styled-components": "2.0.0",
- "babel-plugin-styled-components": "1.1.4"

Not sure if something changed during v2.0.0 release that stopped this to work or else. 
Can someone else confirm/replicate this too?

**Comment by zcei** [comment]
The CSS class names are likely relate to #47?

**Comment by iamrane** [comment]
Same problem here

**Comment by philpl** [comment]
- Enable the `ssr` option for the componentId to be generated from the `displayName`. This is also used for the visible `className`.
- The `displayName` option is on by default and generates a new displayName for each styled component
- Make sure you're on v2.0.0 so that this works well when both options are turned on at the same time

**Comment by elstob** [comment]
Sorry to be a pain but that doesn't seem to be work when generating the JS I'm working with.

I'm using v2.0.0 of SC and v1.1.4 of the plugin, displayName (and now ssr) are both set to true in my .babelrc but I'm still not seeing componentIDs or classNames that reflect the `displayName`. I'm happy to move on with this issue closed if you are all confident that this is working as intended but I wanted to flag it again as it seems not to be working here even with the settings you suggested.

Thanks for your time.

**Comment by nickbalestra** [comment]
^^ that's what we are doing as well I guess

```
[
  'styled-components',
    {
       ssr: true,
       displayName: true // this should be ON by default...
     }
]
```

but we don't see any humanized class-name anymore since v2.0.0 (it used to work with prior RC)
As mentioned earlier, currently running on SC 2.0.0 and plugin 1..1.4

**Comment by elstob** [comment]
Glad to hear it's not just us @nickbalestra, fingers crossed @philpl sees this and saves us. 🍺 for all if so.

**Comment by philpl** [comment]
I'll take another look this evening. Do note that the `componentId` on its own will never be human readable, but the displayName should be. This is why we now concatenate both if the plugin generates them: https://github.com/styled-components/styled-components/pull/821

The only way that you're not seeing any readable displayName is probably the way you're creating your styles components? https://github.com/styled-components/babel-plugin-styled-components/blob/e0b1b4c248f4864c65a1fd368bfc71b36d7407c9/src/visitors/displayNameAndId.js#L35

Is anyone able to post a gist with a `before.js`, `after.js` and a `.babelrc` that demonstrates the issue?

**Comment by elstob** [comment]
Thanks for reopening. Attempting to create a test case gist for this for you has, obviously, shown the correct behaviour. Comparing the output code for this test case against our bundled codebase seems 
to illustrate the difference being between:

Test
```javascript
var StyledDiv = _styledComponents2.default.div.withConfig({
  displayName: 'be__StyledDiv'
})(['color: red;padding: 10px;']);
```

Actual
```javascript
var StyledCheckbox = _styledComponents2.default.div(_templateObject);
```

Which suggests to me that something is happening during our compilation stage that is preventing our actual styled components being built "withConfig". I'll try and play around with our build to see if I can track down what this might be.

**Comment by elstob** [comment]
OK so embarrassingly it seems our build system was using hard coded babel preset and plugin values instead of reading them from our babelrc so even though the config was set up it wouldn't have made a jot of difference. Updating this has given the expected behaviour. I can't speak for @nickbalestra but hopefully his is a similar situation and I'm not the only one with a red face today 🙈
