### ISSUE TITLE
Does this work with Vue (vue-styled-components)

### ISSUE THREAD

**Issue by Jones-S** [styled-components/babel-plugin-styled-components#60]
Hi

I was wondering if this also works with [vue-styled-components](https://github.com/styled-components/vue-styled-components).

I tried it and I am getting weird errors concerning my style.js files with things like `const Section = styled('div', styleProps)`...

I would like to use the debugging feature which adds a identifiable class name in dev mode.

Thanks for any answer.
Cheers

**Comment by philpl** [comment]
No, it won't work ;) While vue-styled-components is directly inspired by styled-components, it's not a 1:1 port. At least not after the release of v2
