### ISSUE TITLE
Add displayName to unnamed components exported as default, based on filename

### ISSUE THREAD

**Issue by vdanchenkov** [styled-components/babel-plugin-styled-components#7]
```jsx
// in Button.js
export default styled.div``
```
should have displayName == 'Button'

I'm going to implement it this weekend.

**Comment by mxstbr** [comment]
Awesome, that's a great idea!

What about doing BEM style naming generally:

```JS
// shared.js

const Button = styled.button``

export { Button }
```

This `Button` could now have a `displayName` (and identifier, thus class) of `shared__Button-asdf123`. That way finding components becomes really really easy!
