### ISSUE TITLE
Component display name appears twice in single CSS class

### ISSUE THREAD

**Issue by andrewtpoe** [styled-components/babel-plugin-styled-components#73]
When using `babel-plugin-styled-components`, the display names in the identifying CSS classes are being doubled up. It appears this problem may actually go deeper and be caused by the display names themselves being doubled.

This screenshot is from the React dev tools of [a very simple app](https://andrewtpoe.github.io/sc-babel-bug/) I put together to demonstrate this problem. You can find the code [here](https://github.com/andrewtpoe/sc-babel-bug).

![screen shot 2017-07-10 at 5 54 48 pm](https://user-images.githubusercontent.com/11183459/28041857-eae8dd44-6598-11e7-9dba-17a90b1a1b13.png)

I now have 3 sites where I am attempting to use this plugin and all behave similarly. The primary site uses a custom webpack config, the others use create-react-app.

Thanks for having a look at this. We are very excited to have the display names in the CSS (once...).

**Comment by mxstbr** [comment]
@philpl any ideas why this is happening? I'm assuming it's not intended.

**Comment by andrewtpoe** [comment]
Definitely not intended. I don't have any ideas concerning it yet. It appears to happen even with the most basic config.

**Comment by philpl** [comment]
It is actually intentional. The `displayName` includes both the guessed component name and the filename: https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/displayNameAndId.js#L39

**Comment by andrewtpoe** [comment]
Is there a way to bypass that behavior? It is very unexpected and undesired.

**Comment by philpl** [comment]
@mxstbr that sounds like a good solution here. Shouldn't be hard to add :) Any takers? Otherwise I'll do it when I have time

**Comment by probablyup** [comment]
@philpl is this fixed? https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/displayNameAndId.js#L40

**Comment by mxstbr** [comment]
Yes, thank you!
