### ISSUE TITLE
`preprocessor` adds extra className when using templated media queries

### ISSUE THREAD

**Issue by bramschulting** [styled-components/babel-plugin-styled-components#76]
I ran into an issue when implementing the templated media queries [as explained the styled-components/styled-components repo.](https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#more-powerful-example)

If I enable `preprocess`, the classNames is added before the media query:

```
{
  "presets": ["next/babel", "es2015", "react"],
  "plugins": [["styled-components", { "ssr": true, "displayName": true, "preprocess": true }]],
}
```
![screen shot 2017-07-13 at 14 40 57](https://user-images.githubusercontent.com/1703323/28166814-b8ae3840-67d9-11e7-8bd2-3cca226853ef.png)

This causes the media query to not work. When I disable `preprocess`, everything works as expected:

```
{
  "presets": ["next/babel", "es2015", "react"],
  "plugins": [["styled-components", { "ssr": true, "displayName": true, "preprocess": false }]],
}
```

![screen shot 2017-07-13 at 14 41 48](https://user-images.githubusercontent.com/1703323/28166851-d592296c-67d9-11e7-8449-78bbde7da953.png)

**Comment by philpl** [comment]
This is expected. The example hasn't been changed to cater for preprocessing since it's still experimental. In v3 it's going to be completely rebuilt from scratch.

If you'd like it to work you'll have to use the css helper inside the media functions and don't just pipe through all arguments

**Comment by philpl** [comment]
https://github.com/styled-components/babel-plugin-styled-components/issues/65
