### ISSUE TITLE
Component name does not show

### ISSUE THREAD

**Issue by SerhiiBilyk** [styled-components/babel-plugin-styled-components#87]
//.babelrc
{
  "presets": ["es2015", "react","env"],
  "plugins": [
    ["styled-components-named"]
  ]
}
//react DevTools
instead of <ComponentName> there are 'styled.div'
Also doesnot work with 'babel-plugin-styled-components'

**Comment by mxstbr** [comment]
You have to use `babel-plugin-styled-components` (`styled-components-NAMED` was turned into this one) and `styled-components` v2.x.

**Comment by SerhiiBilyk** [comment]
"styled-components": "^2.1.2",
  "babel-plugin-styled-components": "^1.2.0",
//babelrc
{
  "presets": ["es2015", "react","env"],
  "plugins": [
     ["babel-plugin-styled-components"]
  ]
}
And still does not work

**Comment by mxstbr** [comment]
I'm afraid I can't replicate this, it's working perfectly for me. What does your component look like?

**Comment by SerhiiBilyk** [comment]
This is my simple component, I see Face component in React DevTools, but I don't see 'FaceWrapper'& 'FaceImg'. I'm not expirenced developer as you and maybe I'm doing something wrong.
https://github.com/SerhiiBilyk/webpack_boiler/blob/develop/src/client/app/components/question/Comment/Face.jsx
Thank you

**Comment by philpl** [comment]
The webpack config in your repo contains a Babel config already, which is probably what confused you

**Comment by SerhiiBilyk** [comment]
@philpl thank you very much, as I said I have not much experience with react&webpack
@mxstbr sorry for issue :)
